### ISSUE TITLE
Use OnVIF to get camera MAC address (and save it) when adding/editing a camera.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#10]
Just FYI, the cgi command for hikvision to do this is ../System/deviceInfo

**Comment by jgarciasacristan** [comment]
I have managed to get the information using  [python-onvif] (https://github.com/quatanium/python-onvif)  against [Mobile Mast] (https://dash.evercam.io/v1/cameras/mobile-mast)
```
jose@joseubuntu:~/onvif$ onvif-cli devicemgmt GetDeviceInformation --user 'admin' --password 'mehcam' --host 149.13.244.32 --port 8100
True: {'Model': DS-2DF7286-A, 'SerialNumber': DS-2DF7286-A20140705CCWR471699220B, 'HardwareId': 88, 'FirmwareVersion': V5.1.8 build 140616, 'Manufacturer': HIKVISION}
```
However when I try to do the same using my little elixir project [onvifex] (https://github.com/jgarciasacristan/onvifex) I get the error below (From the test output)
```
Response GetDeviceInformation hikvision : "<!DOCTYPE html>\r\n<html><head><title>Document Error: Unauthorized</title></head>\r\n<body><h2>Access Error: 401 -- Unauthorized</h2>\r\n<p>Authentication Error: Access Denied! Authorization required.</p>\r\n</body>\r\n</html>\r\n"
```
Once the support for digest authentication is available in HTTPotion as described in [issue 4] (https://github.com/evercam/evercam-media/issues/4) I think I should be able to get the information from the hikvision camera.
For [the AXIS one] (https://dash.evercam.io/v1/cameras/herbst0mast-ptz-mj) invoking GetDeviceInformation is a different story (Need to implement ws-security headers as described in http://stackoverflow.com/questions/10793913/how-to-authenticate-user-in-onvif )

At least GetSystemDateAndTime works in both cameras. :smile:  That will allow me to parse  a successful response.

**Comment by jgarciasacristan** [comment]
Sorry, the OnVIF  command GetDeviceInformation does not show the MAC address.  This is the output that I get when I run http://149.13.244.32:8100/System/deviceinfo (The Hikvision camera)

```
<DeviceInfo version="1.0"><deviceName>IP DOME</deviceName><deviceID>88</deviceID><deviceDescription>IPDome</deviceDescription><deviceLocation>hangzhou</deviceLocation><systemContact>Hikvision.China</systemContact><model>DS-2DF7286-A</model><serialNumber>DS-2DF7286-A20140705CCWR471699220B</serialNumber><macAddress>44:19:b6:4b:f1:a2</macAddress><firmwareVersion>V5.1.8</firmwareVersion><firmwareReleasedDate>build 140616</firmwareReleasedDate><bootVersion>V1.3.4</bootVersion><bootReleasedDate>100316</bootReleasedDate><hardwareVersion>0x0</hardwareVersion></DeviceInfo>
```

**Comment by marcoherbst** [comment]
Hmmm

Right, well Digest auth should be working soon, we've submitted a PR there:

https://github.com/myfreeweb/httpotion/pull/61

So, we think that OnVIF does not offer MAC address? Maybe it's only
possible at time of discovery https://github.com/alb423/wsdiscovery ...
which i think is not so useful to us.

See you tmrw.

M

On 30 June 2015 at 23:43, jgarciasacristan <notifications@github.com> wrote:

> Sorry, the OnVIF command GetDeviceInformation does not show the MAC
> address. This is the output that I get when I run
> http://149.13.244.32:8100/System/deviceinfo (The Hikvision camera)
>
> <DeviceInfo version="1.0"><deviceName>IP DOME</deviceName><deviceID>88</deviceID><deviceDescription>IPDome</deviceDescription><deviceLocation>hangzhou</deviceLocation><systemContact>Hikvision.China</systemContact><model>DS-2DF7286-A</model><serialNumber>DS-2DF7286-A20140705CCWR471699220B</serialNumber><macAddress>44:19:b6:4b:f1:a2</macAddress><firmwareVersion>V5.1.8</firmwareVersion><firmwareReleasedDate>build 140616</firmwareReleasedDate><bootVersion>V1.3.4</bootVersion><bootReleasedDate>100316</bootReleasedDate><hardwareVersion>0x0</hardwareVersion></DeviceInfo>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/10#issuecomment-117365106>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
Good news. Wrong OnVIF command, sorry. Here is the output from the right command "GetNetworkInterfaces"
```
jose@joseubuntu:~/onvif$ onvif-cli devicemgmt GetNetworkInterfaces --user 'admin' --password 'mehcam' --host 149.13.244.32 --port 8100
True: [{'Info': (NetworkInterfaceInfo){
   Name = "eth0"
   HwAddress = "44:19:b6:4b:f1:a2"
   MTU = 1500
 }, '_token': eth0, 'Enabled': True, 'Link': (NetworkInterfaceLink){
   AdminSettings = 
      (NetworkInterfaceConnectionSetting){
         AutoNegotiation = True
         Speed = 100
         Duplex = "Full"
      }
   OperSettings = 
      (NetworkInterfaceConnectionSetting){
         AutoNegotiation = True
         Speed = 100
         Duplex = "Full"
      }
   InterfaceType = "0"
 }, 'IPv4': (IPv4NetworkInterface){
   Enabled = True
   Config = 
      (IPv4Configuration){
         Manual[] = 
            (PrefixedIPv4Address){
               Address = "192.168.1.100"
               PrefixLength = 24
            },
         DHCP = False
      }
 }, 'IPv6': (IPv6NetworkInterface){
   Enabled = True
   Config = 
      (IPv6Configuration){
         AcceptRouterAdvert = False
         DHCP = "Off"
         LinkLocal[] = 
            (PrefixedIPv6Address){
               Address = "fe80::4619:b6ff:fe4b:f1a2"
               PrefixLength = 64
            },
         FromDHCP[] = 
            (PrefixedIPv6Address){
               Address = "fe80::4619:b6ff:fe4b:f1a2"
               PrefixLength = 64
            },
      }
 }}]
```
Working on the authorization headers so I can run the same command from Elixir.

**Comment by marcoherbst** [comment]
Great news.

**Comment by jgarciasacristan** [comment]
Got the the MAC address information using WSSE Authentication in Elixir.  :-)

**Comment by marcoherbst** [comment]
Woohoo, it's downhill from here :) Well done.

M

On 20 July 2015 at 11:59, jgarciasacristan <notifications@github.com> wrote:

> Got the the MAC address information using WSSE Authentication in Elixir.
> :-)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/10#issuecomment-122849164>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
See https://github.com/jgarciasacristan/onvifex/blob/master/test/client/device_management_test.exs for an example on how to collect the MAC address using OnVIF request. (Last test)

**Comment by jgarciasacristan** [comment]
Added "/onvif/cameras/:camera_id/macaddr" route in forked https://github.com/jgarciasacristan/evercam-media repository

**Comment by ijunaidfarooq** [comment]
Hi @jgarciasacristan , I didnt find any `/onvif/cameras/:camera_id/macaddr` route in forked evercam-media repo! Have you removed it?

**Comment by jgarciasacristan** [comment]
Hi @ijunaidfarooq 
Sorry, I think I regenerated the fork, so it may have been lost forever (unless I have it somewhere in my laptop). 
Anyway, it is very easy to read the MAC address. Take a look at https://github.com/evercam/evercam-media/blob/master/test/controllers/onvif_controller_device_service_test.exs#L18 . The OnVIF command you need to invoke is GetNetworkInterfaces .
Then instead of piping into Map.get("Enabled"), pipe into Map.get("Info") | Map.get("HwAddress").

On a side info, I am scheduled for a small surgery procedure next Monday. I will be then off work for two weeks. That will give me plenty of time to fix the OnVIF tests and help in a few issues like this one while recovering. :)

**Comment by ijunaidfarooq** [comment]
Thanks a lot Jose.  And Good Luck for your surgery. Get well soon :)

**Comment by marcoherbst** [comment]
NB: Related: https://github.com/evercam/evercam-admin/issues/240

**Comment by ijunaid8088** [comment]
Its done!
