### ISSUE TITLE
Representative Snapshot Thumbnails

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#100]
This is to be a snapshot from the camera field of view showing a representative field of view. This snapshots are updated every 60 minutes or whenever the camera details are updated by a user. It is not intended to show the live view.

Used, for example, to offer a dropdown list of cameras with small images or to quickly show a layout of cameras on the android app.

It requires 3 new image sizes offered in the Camera Object Model:

thumbnail: 
{
“50”: "https://evercam-camera-assets.s3.amazonaws.com/1011-front-external/snapshots/thumbnail-50.jpg",

“300”:
"https://evercam-camera-assets.s3.amazonaws.com/1011-front-external/snapshots/thumbnail-300.jpg

“640”:
"https://evercam-camera-assets.s3.amazonaws.com/1011-front-external/snapshots/thumbnail-640.jpg
}

When implementing this, if you are struggling with the 60 minute update, we can leave that until later.

M

**Comment by marcoherbst** [comment]
This is the same as #46

**Comment by marcoherbst** [comment]
DIscussed this again with Milos. It might need to be split into different issues. One of which is simply to update the thumbnail every 60 mins. NB Whenever this is done, consider that we would rather not just start filling up infinite  storage again like we were doing when we were capturing 1/min for all cams.

**Comment by mosic** [comment]
Yes, we can delete the snapshot used for the last thumbnail when updating it (and we can check if it has a note of "Thumbnail" for example).

**Comment by marcoherbst** [comment]
I think this isn't important enough. It doesn't seem to be causing any issues at the moment. Closing.
