### ISSUE TITLE
Improve Compare & Jpeg Filename

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1003]
Evercam- Compare-Dorset-Point-From-12032018-090812-To-12042018-090811.gif

Evercam-Snapshot-Dorset-Point-12032018-090812.jpg

**Comment by azharmalik3** [comment]
Assigning this task to @ijunaid8989 because he is already working on compare speed up the task.

**Comment by azharmalik3** [comment]
It's done.
