### ISSUE TITLE
Identify the green shapshots and do something about them.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#101]
Discussed by email with @shankardevy

**Comment by eugenehp** [comment]
There is a way to use the MD source code for that, it can be implemented by
adding one method to the code.

**Comment by shankardevy** [comment]
@eugenehp I am interested to know you proposal? Do you mean checking the RGB value of each pixel in the image? how does it work for variations of green color? or if some other camera provides gray image instead of green?

**Comment by eugenehp** [comment]
@marcoherbst @shankardevy there is a way to implement such method in C++ code, and of course green variety of colours would be easier to catch at first.

The approach would be something like: over 80% of space is gray color from #aaaaaa to #cccccc

**Comment by marcoherbst** [comment]
Not needed
