### ISSUE TITLE
Remove all unusued Makes & Models 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1011]
@azharmalik3 I think this was done before, no?

In any case, can you please do it.

m

**Comment by azharmalik3** [comment]
@marcoherbst Last time we deleted all same URL models and created one default model.

Now you want to delete everything which is not using.

e.g: if Panasonic models are not using then delete Panasonic vendor and models. No need to keep default one?

**Comment by marcoherbst** [comment]
Yes, let's do it.

**Comment by azharmalik3** [comment]
Removed all unused makes and models.
