### ISSUE TITLE
Add all error alerts to Sumologic

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#1027]

**Comment by marcoherbst** [comment]
@azharmalik3 I know you have been working on this. IT might help if you add to this ticket with a list of all the places and/or approaches you can think of, otherwise the ticket is quite vague.

**Comment by azharmalik3** [comment]
Added a few other places which area need to keep an eye.
Get /cameras
Camera /create
Share /create
Archive /create
Compare /create

Also, added error alerts for (500, 400) to sumologic but sumo does not contain enough information about error. Like: `request_id=2lndvh7i52d1pv19kg334i55 [info] Sent 500 in 3ms`

**Comment by azharmalik3** [comment]
Closing this because of all alerts scheduled including 500 errors other unhandled errors.
