### ISSUE TITLE
Stop streaming when idle more than 2 minutes.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#1032]
Dashboard just paused stream and gives the display a `Stream is paused, User is inactive for more than 2 minutes`.

Use the same idea to stop/pause stream from the server side and update active video session table.

**Comment by marcoherbst** [comment]
@azharmalik3 done? if so please close

**Comment by azharmalik3** [comment]
Done. Now, system stopped streaming in case of idle or 0 active connections.
