### ISSUE TITLE
Swagger minor improvement.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1036]
I was about to delete a doc with the following info:

Snapshot Nearest Endpoint
URL: /v1/cameras/{camera-id}/recordings/snapshots/{timestamp}/nearest

Parameters:
camera_id
timestamp **(can be either unix or ISO). like (1479780886 or  2016-11-22T02:14:46.000Z)**
api_id
api_key

Description:
**Returns the snapshot nearest to a given timestamp (within that hour). It does not check outside of the specified hour.**

When I thought it would be nice to add the relevant parts in bold to our swagger docs.

https://media.evercam.io/v1/swagger/index.html#/Recordings/EvercamMediaWeb_SnapshotController_nearest

@azharmalik3 I'd like you to assign this to the relevant person.

**Comment by ijunaid8989** [comment]
its done.
