### ISSUE TITLE
Remove Default Shared camera on new accounts

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1045]
... needs discussion before doing. Also remove it retrospectively.

**Comment by marcoherbst** [comment]
Delete all shares of WickloCam for users who are not logged in for more than 1yr

**Comment by azharmalik3** [comment]
@marcoherbst 
P2: Created google sheet of all users who have WicklowCam share.

**Comment by azharmalik3** [comment]
Yes, removed.
