### ISSUE TITLE
Zoho Support Sign In

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1050]
https://www.zoho.com/desk/blog/remote-authentication.html

**Comment by azharmalik3** [comment]
@marcoherbst Zoho support remote authentication completed and deployed.

But Zoho does not allow to login agent as enduser.
![image](https://user-images.githubusercontent.com/6176136/50475245-da87bb80-09e5-11e9-9b56-b7a73c783706.png)

Like marco@evercam.io is an Zoho agent and he cannot login as enduser.

You can test this for `azhar@evercam.io`.

**Comment by marcoherbst** [comment]
Looks good, tks.
