### ISSUE TITLE
Seaweed Security

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1057]
... it's not good enough yet.

**Comment by marcoherbst** [comment]
https://github.com/chrislusf/seaweedfs/wiki/Security-Overview

**Comment by azharmalik3** [comment]
I have tested the weed security system on the local machine and it works. But they implemented security on volume server only and not implemented on master API and filer API yet.

We need to wait until they implement security for filer API because we are using filer API to communicate with seaweed.

**Comment by marcoherbst** [comment]
I'm closing this, I'm happy with what you've done. Thanks @azharmalik3
