### ISSUE TITLE
Don't be sending from support@evercam.io any more

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1079]
Use no-reply@ instead  (We've done half of this task already)

Here's a list:

- [ ] X has shared camera Y with you
- [ ] Camera share request  (Bcc: marco@, vinnie@, erin@)
- [ ] Password reset
- [ ] Camera is now online / offline
- [ ] Camera create (Bcc: marco@, vinnie@, erin@)
- [ ] Confirmation
- [ ] Camera offline reminder
- [ ] X has accepted share request
- [ ] X did not accept share request  (Bcc: marco@, vinnie@, erin@)
- [ ] Archive completed / failed
- [ ] Snapshot extractor started / completed

Send from snapmail@

- [ ] Snapmail

Emails send to @marco @vinnie @azharmalik3 @ijunaid8989 

- [ ] Cloud-recording changed
- [ ] Archive failed with error message

There's more. We'll add to this list as it goes. @azharmalik3 @ijunaid8989 @affan00 best that you're all aware of this. This task will come in the near future.

**Comment by azharmalik3** [comment]
@marcoherbst updated list of emails we are sending to customers.

**Comment by azharmalik3** [comment]
Done.
