### ISSUE TITLE
Cloud-recording calendar highlight wrong days

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#1083]
Date overlaps for 
When system converts DateTime from camera timezone to UTC it overlaps to next or previous date (e.g from: 8 March 06:00, to: 9 March 05:59, 8th March overlap 9th march) which caused to highlight the empty day.

Check the following camera: https://dash.evercam.io/v2/cameras/danne-dxmrh/recordings

**Comment by marcoherbst** [comment]
@affan00 this might be related to an issue I reported to you ... just FYI

**Comment by azharmalik3** [comment]
Days endpoint gives wrong days for `-` offset timezone. Made changes in /days endpoint to return only those days who have recordings.
