### ISSUE TITLE
Database cleanup

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#1084]
Add migration to remove marked tables.

![evercam_db_schema](https://user-images.githubusercontent.com/6176136/54585888-2ffbc380-4a3d-11e9-957f-9fa20d17c639.jpg)

Code cleanup for deleted tables in models, server and admin-section.

**Comment by marcoherbst** [comment]
@azharmalik3 anything more that could be done here? or ready to close?

**Comment by azharmalik3** [comment]
@marcoherbst Completed and we can close.
