### ISSUE TITLE
Filer Backup - get it working again

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1091]

**Comment by ijunaid8989** [comment]
The process of creating the metafile for current filer is running (within a screen), and it may take more than a day until then we cannot update(start or stop seaweedfs node.) to the latest version and use the compaction `mbs per second` feature.

Also, Chris suggested measuring disk speed during compaction and then set half of that number to `-volume.compactionMBps` for server and `-compactionMBps` for volume.

**Comment by ijunaid8989** [comment]
First Filer metafile of `65.2G` has been added to hetzner box.

I will repeat this process each weekend.
