### ISSUE TITLE
Zoho Contacts by Registration Date

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1107]
Consider a method to find all contacts who are users who have registered in the last X days.
(or visited in the last X days).

This may require a new field ...

**Comment by azharmalik3** [comment]
@marcoherbst we have a field in Zoho `Created Time` to find all contacts who registered in the last XX days.

Also, have a field `Most Recent Visit` to get all contacts who visited in the last XX days.

**Comment by marcoherbst** [comment]
Adding an "Evercam Registration Date" as a custom field auto-filled.

**Comment by azharmalik3** [comment]
@marcoherbst completed.

**Comment by marcoherbst** [comment]
Hmmm ... some users missing ... keep trying.

**Comment by azharmalik3** [comment]
Done. Added missing users to Zoho.
