### ISSUE TITLE
Archive Compare Thumbnail add a line

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1110]
Add a thick red vertical line and arrows like   < | >  to the thumbnail for a compare in archives.

Also, do this retrospectively.

**Comment by azharmalik3** [comment]
Added a vertical line with arrows to the compare thumbnail.

![image](https://user-images.githubusercontent.com/6176136/60007049-0204cb80-968b-11e9-9ab0-4d61dcf5420c.png)

**Comment by marcoherbst** [comment]
x3 size of arrows in the thumbnail
x0.5 size of logo on thumbnail and video
re-run script for all old ones.

Debug: https://dash.evercam.io/v2/cameras/hikdemo/archives/steph-twhma

**Comment by azharmalik3** [comment]
![image](https://user-images.githubusercontent.com/6176136/60430015-c4b5b600-9c15-11e9-925a-fbc2420fc9b0.png)

Done.
