### ISSUE TITLE
Allow apostrophe and suitable special characters in email regex.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#1120]
Right now we are not allowing apostrophe and many other suitable special characters in the email regex. kindly update the regex to allow such special characters like an apostrophe.

Suitable regex: 
^(?!.*\.{2})[a-zA-Z0-9!.#$%&'*+"/=?^_`{|}~-]+@[a-zA-Z\d\-]+(\.[a-zA-Z]+)*\.[a-zA-Z]+\z*$

**Comment by azharmalik3** [comment]
Done.
