### ISSUE TITLE
Clean the code to point newly added seaweedfs filer(s)

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#1124]
This is the basic PR for when you add a new filer , and those are the places at which you need to change the seaweedfs instance

https://github.com/evercam/evercam-server/pull/1018/files.

https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/storage.ex
There is 26 Occurrence of seaweedfs current filer in the file, which will be needing an update.

also this https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/storage.ex#L413

we need to change the code in such a way, that there should be only one place, where we will change the filer instance, for next time and all the next coming filers.

**Comment by azharmalik3** [comment]
Removed all static code of storage servers and added servers info into DB.
