### ISSUE TITLE
Add Image as Attachment(s) to Snapmail as well as embedding.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#1180]
This is to deal with the customers who cannot see the image properly on Outlook 2013 because it is alwasy 100% width.

@azharmalik3 can you assign this task ... it would be great to get it done in next 2-3 days.

**Comment by ijunaid8989** [comment]
https://github.com/evercam/evercam-server/pull/1181

it's very minor change.

**Comment by marcoherbst** [comment]
Great, thanks.

**Comment by marcoherbst** [comment]
@ijunaid8989 when this is deployed, please let me know and we'll close the issue.
tks. m

**Comment by ijunaid8989** [comment]
its done.
