### ISSUE TITLE
New cloud recording clip email is not showing evercam logo & low quality camera thumbanail

### ISSUE THREAD

**Issue by JaviCT** [evercam/evercam-server#1226]
![image](https://user-images.githubusercontent.com/19703794/69730862-badea300-1120-11ea-9b6b-2e86a28a316b.png)

**Comment by marcoherbst** [comment]
And while you're at it, give us a nice Evercam watermark in the bottom right hand corner approx 1cm squared.

**Comment by ijunaid8989** [comment]
We settled on saving the first image from seaweedfs for mp4 as a thumbnail, as well as I, used this command to create watermark on the bottom right https://github.com/evercam/evercam-server/commit/b6a621eea185679d203743ebb3deae89933f041b

**Comment by ijunaid8989** [comment]
its done
