### ISSUE TITLE
Duplicate onvif commands under /cameras/:id/onvif/  & (Support NVRS)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#131]
Here's the list:
http://www.onvif.org/onvif/ver20/util/operationIndex.html

These 2 are equivalent:
http://www.onvif.org/onvif/ver10/device/wsdl/devicemgmt.wsdl#op.GetDeviceInformation
GET /cameras/:id/onvif/GETDeviceInformation

on Q, I wonder if this might be better done under: /devices/ rather than /cameras ....

m

**Comment by jgarciasacristan** [comment]
/devices/:id/onvif/v20/OnvifOperationName as we cover recording devices as well.

For example for GetDeviceInformation of mobile-mast would be something like

https://api.evercam.io/v1/devices/mobile-mast/onvif/v20/GetDeviceInformation.

When adding a camera, the camera will not be avaikabke in the DB so current Onvif calls will fail. We need to figure out a way to provide host/port/username/password available to the connection. One way can be to check for query params if the id is not available in the DB (See http://hexdocs.pm/plug/Plug.Conn.html)

**Comment by marcoherbst** [comment]
hmmm . I find this a bit confusing. Do you want to try to explain it to me? It sounds important.

**Comment by jgarciasacristan** [comment]
The way the OnVIF API endpoints work is by reading host port username and password from the Cameras information in the DB as only the camera-id is provided. We cannot  use OnVIF APIs as they are currently implemented to discover camera information as the camera-id is not yet available in the DB. The solution is to provide host/port/username/password explicitly as part of the API call in these scenarios. Query params in the API call is one way to bypass the DB.  Does that make sense?

**Comment by marcoherbst** [comment]
This is like https://dash.evercam.io/swagger#!/cameras/POST_cameras_test_format which requires no auth and needs all parameters.

**Comment by jgarciasacristan** [comment]
Yes. That is the idea.

**Comment by marcoherbst** [comment]
The way this issue is written seems like it doesn't matter anymore. 
We probably should support OnVIF, but it's not a current issue. Closing.
