### ISSUE TITLE
Staging environment

### ISSUE THREAD

**Issue by fteem** [evercam/evercam-server#135]
_This is an issue about all of the apps that form Evercam.io, not just this repo._

After a discussion with @mosic and @marcoherbst regarding setting up a staging environment, these are the ideas that our discussion has revolved around:
## Purpose

Right now, when developing new features or fix bugs, we create a feature branch, do the work, create a pull request, get the code reviewed and we merge the branch into master. After that, we deploy to production and check if our work works directly on production. If the branch breaks anything, we rollback the branch. 
It's in our opinion that this process is quite brittle and instead of possibly breaking production, we need to have an environment that we can break without causing **any** downtime. This is a good reason to start thinking more seriously about a staging environment and the benefits from having it. 
## Development flow

With a staging environment in play, the development flow will not change much. Since we already use TravisCI, which builds any branches (including master), getting a staging environment won't change much. 

The ideal flow would be:
- A feature branch is created
- A pull request is created, which is built by TravisCI.
  - If the build is green, and the code review approves the work done in the PR, it will get merged into master. 
- TravisCI builds master again, reporting the status (green/red).
  - If green, TravisCI automatically deploys the app to staging.
- When master is deployed to staging, we can log in (to staging env) and click around to check how our branch works from a user perspective. With this step, we eliminate any possibilities of breaking production (and rolling back).
- If everything goes well, we can then proceed to deploying to production, knowing that our branch will fit in nicely.
## Side-effects
- Master will always be green.
- Master will never be broken (or, unstable). 
- We will be more confident about our code. It can never get perfect, but it will definitely improve.
## Overhead
- The dev team will have to commit to maintaining the environment. 
  I don't see this as much of a problem, because it will basically be a replica of production, in terms of code and infrastructure. It will be more time-consuming than just taking care of one env (production), sure, but there are other benefits.
- More servers == More $$$.
## Provisioning

One important thing that needs to be taken care of is having dummy data in the database. We can achieve this in three ways (that I can think of right now):
1. We get a snapshot of the database(s), remove the live camera urls and other sensitive data and create the database with that snapshot.
2. Write seed (dummy) data just for staging and run the scripts on the server(s).
3. Get the apps running in staging env and create the data manually, just like a normal user would.  

Thanks for reading :-)

Thoughts?

**Comment by marcoherbst** [comment]
@azharmalik3  you've done some related work. Do you feel this issue can be closed? Or should be edited ?

**Comment by azharmalik3** [comment]
Yes, we can close this issue now.

**Comment by marcoherbst** [comment]
@azharmalik3 would you mind please explaining here what you've done. It will help for posterity.

**Comment by azharmalik3** [comment]
Bought Hetzner vServer with ubuntu-16.04 for staging server. Made some changes in [evercam-devops](https://github.com/evercam/evercam-devops/compare/changes_for_new_server_configuration?expand=1) for installation on ubuntu 16.04. 

Installed all dependencies (erlang, elixir, seaweedfs etc) using DevOps. Created database with dummy data. 

Finally, deployed evercam-server.
