### ISSUE TITLE
Add application monitoring and collecting metrics

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#14]
Currently we only have server-level monitoring (using New Relic). It would be great if we had some more insight into application performance, especially more granular memory metrics (how much is used by processes, ETS, atoms etc.)

I imagined something like this: https://medium.com/@mschae/measuring-your-phoenix-app-d63a77b13bda, but Eric's [gaze](https://github.com/ericmj/gaze) app may also be useful as a reference: 

![image](https://cloud.githubusercontent.com/assets/1229422/8503201/c4a8ed4a-21bb-11e5-9053-03e0aae3cddb.png)

**Comment by marcoherbst** [comment]
Thanks Milos. 
@gjaldon this is a stub where we plan to add thoughts around the issue we discussed :)
m

**Comment by gjaldon** [comment]
Copy that! Will post here in case I have any questions. :)

**Comment by gjaldon** [comment]
@mosic thanks for the links above. Really helpful! 

@mosic @marcoherbst was setting up evercam-media and kept getting `Response isn't an image for camera 'evercam-remembrance-camera'`. Found that I needed to run `mix evercam.seed` but needed to run migrations in evercam-api first. 

For me to run migrations, I'll need to satisfy the ENV vars needed in `settings.yaml` in evercam-api. Do you guys have keys/account details you can share for all the required ENV vars in evercam-api?

Just detailing what I went through to help document it somewhat for others. I commented out `check_camera/1` task in `EvercamMedia.Worker` so I don't need to do the above. 

Will continue to work on this in the next few days.

**Comment by marcoherbst** [comment]
That sounds exciting.

Milos will give you the proper answers to your Q's. One thing to be aware
of is that cameras will ocassionally give bad responses, especially those
that are heavily loaded. Sometimes 2/3 of responses will be "bad". The
problem you've reported might be something totally unrelated to this.

Sounds great, you should hear from Milos tmrw morning GMT. :)

M

On 5 July 2015 at 22:36, Gabriel Jaldon <notifications@github.com> wrote:

> @mosic <https://github.com/mosic> thanks for the links above. Really
> helpful!
>
> @mosic <https://github.com/mosic> @marcoherbst
> <https://github.com/marcoherbst> was setting up evercam-media and kept
> getting Response isn't an image for camera 'evercam-remembrance-camera'.
> Found that I needed to run mix evercam.seed but needed to run migrations
> in evercam-api first.
>
> For me to run migrations, I'll need to satisfy the ENV vars needed in
> settings.yaml in evercam-api. Do you guys have keys/account details you
> can share for all the required ENV vars in evercam-api?
>
> Just detailing what I went through to help document it somewhat for
> others. I commented out check_camera/1 task in EvercamMedia.Worker so I
> don't need to do the above.
>
> Will continue to work on this in the next few days.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/14#issuecomment-118668966>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by mosic** [comment]
@gjaldon I'll work on getting the dev setup working tomorrow so that shouldn't be an issue. For now, you can try with dummy credentials given in https://github.com/evercam/evercam-devops/blob/master/.env but I think it would still end up erroring on migration. 

Like @marcoherbst just mentioned, getting that response is "normal", that just means the camera is online but responded with a message saying "Device Busy" or similar, and not with an image like we would expect.

**Comment by marcoherbst** [comment]
@ijunaidfarooq I think this issue might be a black hole for you, for now, I'm moving it to a future milestone.

**Comment by marcoherbst** [comment]
https://hackernoon.com/a-tour-of-elixir-performance-monitoring-tools-aac2df726e8c#.rq0sp0663

**Comment by ijunaid8088** [comment]
https://elixirforum.com/t/how-do-you-monitor-profile-your-live-elixir-phoenix-apps/1439/11

**Comment by marcoherbst** [comment]
Closing this. It's vague and realistically we're not working on it.
