### ISSUE TITLE
Motion Detection uses NIF, it should use ports to reduce crashing

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#163]
From Shankar:

Motion detection uses erlang nif extension. This is not ideal for our use case because a single corrupt jpeg image could crash the entire app including the supervisor process which takes care of restarting process crash. Only an external restart of the app can work on this scenario. Due to this, it's not a good choice to use nif. Both Milos and I were not aware of these implications when Eugene wrote this nif library and we noticed the cause only later when we saw repeated crashes in the logs and discussed about it. 

A better solution is to use erlang ports which doesn't crash the app for corrupt images. Since Milos and I were not comfortable writing MD using ports at that time (given our less experience on the same and other priorities), we decided over a call to check for valid jpegs and pass only valid images to MD library and ignore the rest. This worked considerably well but I am sure there are still some edge cases where the images are not valid. The way we check for valid jpeg is by checking jpeg magic numbers. The better option is to use Ports and avoid crashes and not trust any input as valid jpeg.

cc @mosic

**Comment by mosic** [comment]
I've "solved" this by trapping the error in the motion detection script so the NIF doesn't crash the application. We can revisit Ports at a later date.

**Comment by mosic** [comment]
Reopening as a reminder for future Motion Detection implementation. I'm still of the opinion that we should avoid using NIFs, and prefer using Ports.

One additional idea: we could have a separate (micro-)service which just receives the images, does computation and returns back the result. It could be written in something other than Elixir/Erlang. This seems best if you want to reuse some off the shelf solution, e.g. Node.js app.
