### ISSUE TITLE
Have all outbound requests coming from a single (or range of) IP address.

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#182]

**Comment by marcoherbst** [comment]
Moving this to December Milestone as Azhar will look into it now ....

**Comment by marcoherbst** [comment]
At first reading it seems Failover IP might not be available on VServers: 
https://wiki.hetzner.de/index.php/VServer/en#Is_it_possible_to_order_additional_IPs.2C_failover_IPs_or_subnets.3F @azharmalik3  @ijunaid8088

**Comment by marcoherbst** [comment]
@azharmalik3  , I'm now very confident that this is not an option for us.  Move on to something else, we can leave this issue open as a placeholder as it would be a nice problem to solve, someday.

**Comment by marcoherbst** [comment]
I changed the title of this issue as it may have nothing to do with the failover facility of Hetzner.

**Comment by marcoherbst** [comment]
This exists in another issue.
