### ISSUE TITLE
Replace GenEvent with GenStage

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#190]

**Comment by mosic** [comment]
After reading a bit about it (http://elixir-lang.org/blog/2016/07/14/announcing-genstage/), I think we would replace our usage of `GenEvent` with `GenStage`. This is not urgent, but it could improve the supervision and stability of the system, especially at higher loads.

**Comment by marcoherbst** [comment]
Related: https://www.youtube.com/watch?v=M78r_PDlw2c&index=8&list=PLWbHc_FXPo2ivlIjzcaHS9N_Swe_0hWj0 ?

**Comment by azharmalik3** [comment]
Replaced GenEvent with GenStage.
