### ISSUE TITLE
User Activity Logs - visible to user

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#224]
Add some form of user activity logging for major events.

Begin with a Google Doc to explain current situation and 2 or 3 different ways it could be improved.

Things like:
- [x]  Update Profile
- [x]  Add / Edit / Delete Camera
- [x]  Share Camera
- [x]  Create Archive
- [x]  Change Password
- [x]  Login

.... etc. Hopefully it will be fairly obvious and you'll find a nice way of implementing this.

Related to: https://github.com/evercam/evercam-server/issues/522  and https://github.com/evercam/evercam-server/issues/638

**Comment by marcoherbst** [comment]
NB . This would include a Dashboard interface and some events would also need to be created by the dashboard & mobile apps.

**Comment by ijunaid8088** [comment]
I have created the relevant endpoint to show the activities specifically done by the user and its working fine for now.

Next step is to build an interface in dashboard to show those activities by using that endpoint.

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-dashboard/issues/1522

**Comment by azharmalik3** [comment]
@ma All possible logs covered except billing because we are not using billing section at the moment.
