### ISSUE TITLE
Reconsider how we use Unix timestamp for recordings

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#235]
.... currently when we send a request such as:
https://api.evercam.io/v1/cameras/gpocam/recordings/snapshots?from=1463994000&to=1463997600&limit=3600&

we don't get a response outside of that range ... this is due to how we are converting unix timestamp to deal with timezone ... which kind of defeats the purpose ....

This'll need a look at someday.

**Comment by marcoherbst** [comment]
http://michal.muskala.eu/2017/02/02/unix-timestamps-in-elixir-1-4.html

**Comment by ijunaid8088** [comment]
Nice! We are also using `Calendar`
In oldest version of this post, He was not using `Calendar`, but erlang modules to create timestamps.

**Comment by marcoherbst** [comment]
Duplicated
