### ISSUE TITLE
Provide a nicer default thumbnail

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#239]
It would be nice if we had a better default thumbnail for cameras which are offline and have no snapshots, the current image looks like something went wrong, even though this is a normal/expected situation:

![image](https://cloud.githubusercontent.com/assets/1229422/15604730/30a82bde-2402-11e6-8870-a390408f3c67.png)

One such camera: https://dash.evercam.io/v1/cameras/carrolls-packing-cam/details

It would be a big plus if it didn't stick out as much when looking at a user dashboard with other cameras which have a proper thumbnail. Maybe we could use a darker background?

@marcoherbst

**Comment by marcoherbst** [comment]
Would "Waiting to receive first snapshot" be appropriate text? If so, I'll ask @affan00 to create a suitable image.

**Comment by marcoherbst** [comment]
@mosic

**Comment by mosic** [comment]
Yes, that sounds better. Do you agree that it would be nicer if the image was darker?

**Comment by marcoherbst** [comment]
I've no strong opinion on the light / dark .. yes, you're right it would be more appealing to the eye. 

I am going to suggest to @affan00 that he uses the vendor-model thumbnail in this placeholder with a text overlay. Sound ok?

**Comment by mosic** [comment]
Sure, sounds good.

**Comment by marcoherbst** [comment]
This is 100% a dashboard task, right? If you think Affan could do with some help in knowing exactly when to show this image and how you'd like it implemented, then here would be a good place to let him know. It might even get done today, if it's small and we're lucky.

**Comment by mosic** [comment]
No, the image is served from evercam-media - if you request a thumbnail when there is none you get this image and the response code is 404.

**Comment by marcoherbst** [comment]
Not really relevant anymore. Closing.
