### ISSUE TITLE
Onvif request errors out when the response body is empty

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#251]
This is currently the case with `evercamfsd` camera when requesting presets. The `response.body` is empty on this line: [onvif_client.ex#L40](https://github.com/evercam/evercam-media/blob/a725a5fe55c841ccaf4fc7d33c74bf38b5d724d7/lib/evercam_media/onvif/onvif_client.ex#L40), which creates this error:

``` elixir
** (exit) {:fatal, {:expected_element_start_tag, {:file, :file_name_unknown}, {:line, 1}, {:col, 1}}}
```

This is caused by passing `[]` into `:xmerl_scan.string`.

@jgarciasacristan I'll assign this to you, take a look when you have time for it.

**Comment by jgarciasacristan** [comment]
Hi Milos,
Can you email me the camera details (url, username, password)?. Strange
that the body is empty. It should be easy to fix, though.

**Comment by mosic** [comment]
Sure, I just shared the camera with you: https://dash.evercam.io/v1/cameras/evercamfsd

**Comment by marcoherbst** [comment]
@jgarciasacristan @liutingdu @Zulqarnain-Mustafa  ... it would be great to have this sorted, I suspect it might be involved in some crashes in the Android app.

**Comment by jgarciasacristan** [comment]
This is the output from getPresets
%HTTPotion.Response{body: "", headers: ["Content-Length": "0", Date: "Sat,
11 Aug 2012 00:57:07 GMT", Location: "/cookiechecker?uri=/onvif/PTZ",
Server: "lighttpd/1.4.30", "Set-Cookie":
"AIROS_SESSIONID=385d8dc868a41aeaba86c31501d48d69; Path=/; Version=1"],
status_code: 302}

I have added follow_redirects: :true as described in
https://hexdocs.pm/httpotion/HTTPotion.html but it still returns the same
302 status and no body.
Any ideas?

**Comment by jgarciasacristan** [comment]
It turns that it was fixed in https://github.com/myfreeweb/httpotion/pull/71
Updating httpotion to 3.0.0 in my fork and I will test it again.

**Comment by mosic** [comment]
Yeah, I was about to write that. Btw we're using `HTTPoison` for everything else, so if you see an opportunity to replace `HTTPotion` with it for Onvif requests, that would be great.

**Comment by jgarciasacristan** [comment]
I'll try to replace it this weekend.

**Comment by mosic** [comment]
Great, let me know if you hit some roadblocks.

**Comment by ijunaid8088** [comment]
This was an issue in httpotion. As we have moved to HTTPoison. And I have replaced httpoison in onvif modules and over all repo already. So this issue isn't valid anymore.
