### ISSUE TITLE
Best approach to refreshing the /cameras page on dash and mobile

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#274]
This is a placeholder to remember to discuss this with Milos. In particular we will need our mobile apps to at least be refreshing the thumbnail, possibly later playing a reduced rtsp stream. @Zulqarnain-Mustafa this is relevant to you. 

Considering things like - turning off when not watched & the ability to throttle this.

**Comment by Zulqarnain-Mustafa** [comment]
Hi @marcoherbst  i think you are talking about this screen, where we load the camera thumbnails, We refresh the thumbnail images in 3 case:
1-Application launched and grid view loaded
2-User manually refresh the grid view
3-when user turn off/on the offline cameras from side navigation view or settings

If i misunderstood or missing anything please let me know.

![simulator screen shot jul 11 2016 11 35 09 am](https://cloud.githubusercontent.com/assets/8174314/16721832/d4a29e28-475b-11e6-8926-8985dcf98814.png)

**Comment by marcoherbst** [comment]
That's right.

And, if you look at how other apps tend to do it, rather than leaving as tatic snapshot, they auto-refresh or even play streams on this view.

I think as we have only high-res streams, we cant, yet, play them, but I think we could cycle through the cameras, one by one, and continuously refresh them (or something like that).

It will use more data, but I think it's better.

This is also a question for the dashboard which is worth discussing with Affan. He has an issue open somewhere where this is a setting under "Settings" in dash left nav.

**Comment by Zulqarnain-Mustafa** [comment]
@marcoherbst  we can update the image in iOS, i have done that with the help of SDWEBIMAGE, Here is the link to library:
https://github.com/rs/SDWebImage
Please read under the heading:
**Handle image refresh**
It is same case as our URL is static but image changes.

**Comment by Zulqarnain-Mustafa** [comment]
@mosic can you please tell us after how many seconds camera thumbnail image updates?

**Comment by mosic** [comment]
@Zulqarnain-Mustafa Every time a new snapshot is saved (via recordings, timelapse, snapmail, POST request) the thumbnail is updated. Also, every time the thumbnail is requested we make a background request to update it, so the next time you request it you'll get a new image.

**Comment by marcoherbst** [comment]
looks good.

@Zulqarnain-Mustafa it might make sense to have a go at this then relatively soon ... if it looks nice, we can apply the learnings to android & web.

m

**Comment by Zulqarnain-Mustafa** [comment]
@mosic  thanks

**Comment by marcoherbst** [comment]
Close. Outdated.
