### ISSUE TITLE
We make multiple requests when we open a camera - reduce?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#281]
e.g. we make a Motion Detection request. 

If GET /cameras  (and /cameras/{ID} were more full featured, then we could have just 1 AND we could improve our interface as @affan00 wants to do. (e.g. showing CR status in left nav.

This is also true for vendor model data and CR settings.

**Comment by ijunaidfarooq** [comment]
I think @affan00 can improve that left nav by now because I already have added CR settings with `camera` json returns from `/cameras` endpoint.

**Comment by marcoherbst** [comment]
Ah, that's great. Yes, I remember now. 
Good, I'll keep this ticket open as one of the things I expect we'll do once we're migrated off API is to review these endpoints further.

**Comment by ijunaidfarooq** [comment]
@marcoherbst : 
Right now we are doing these queries against `/cameras/:id`
`FROM "cameras"`
`FROM "vendor_models"`
`FROM "vendors"`
`FROM "users"`
`FROM "access_rights"`
`FROM "access_tokens"`
`FROM "cloud_recordings"`
`FROM "motion_detections"`

these all above are necessary ones! Even now we have MD on some of few user accounts.

other than that all other requests are being sent from the dashboard for each tab. Details/Recording/Motion/sharing/logs/Archives

**Comment by marcoherbst** [comment]
The point here is that we can improve the response of /cameras so that it is not required to make (from the dash) so many requests. 

If all of this info was returned in the /cameras endpoint then I could imagine things working a little faster.

Optional: Verbosity flag.

**Comment by marcoherbst** [comment]
And, it's ok to put this into v.1.0.2.... I'll do that now.

( My guess is there will be a very similar ticket in v2.0 where we consider making breaking changes to /cameras endpoint and  /cameras/{camera-id}

**Comment by marcoherbst** [comment]
Bit vague, I'm closing this.
