### ISSUE TITLE
Lepton (Dropbox), relevant?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#291]
https://blogs.dropbox.com/tech/2016/07/lepton-image-compression-saving-22-losslessly-from-images-at-15mbs/

Sounds good, eh?

@mosic could you envisage this being used? Or incorporated into seaweed ?

**Comment by mosic** [comment]
@marcoherbst It does sound good. I'm suspect that using it in evercam-media wouldn't be worth the CPU usage, but having it built into seaweed would be great.

**Comment by marcoherbst** [comment]
Sounds right. So, really we'd need to run past chrislusf to see if he believes it would be a fit for his project?

Well, I don't feel well equipped for that conversation, you're very welcome to if you think it's appropriate.

Meanwhile, I'll keep this issue on a more distant milestone.

**Comment by marcoherbst** [comment]
We'll look into this sort of thing another day. ...
