### ISSUE TITLE
Documentation Step 1

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#297]
Ok @ijunaidfarooq  @azharmalik3 , let's go:

http://elixir-lang.org/docs/master/elixir/writing-documentation.html

For now, just document one thing well ... to set the standard.

http://docs.evercam.io/api-reference.html

**Comment by marcoherbst** [comment]
We agreed this is something that can be run periodically and will generate docs that are stored in a separate repo. Sounds fine to me.

**Comment by ijunaidfarooq** [comment]
We are going to document the important modules only. 

i.e Camera / User / CameraShare / CameraShareRequest / Snapshot

**Comment by ijunaid8088** [comment]
I have discussed with Marco about this issue to move it to the future milestone.

for other to follow up this issue.

I have tried to write the documentation twice with 2 different ideas but it didn't seem as efficient as I was expecting it to be. 

http://docs.evercam.io/

as Our some of the modules like `SnapShot` are complicated enough to elaborate in some brief notes.

**Comment by marcoherbst** [comment]
Closing.
