### ISSUE TITLE
Use gathered MAC addresses to improve our Vendor MAC data in order to improve discovery.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#31]
Discovery of cameras relies frequently on MAC address to determine the likely Camera Vendor and, also, to determine whether or not a discovered camera has been already added  to Evercam.  Therefore, it would be nice if we knew, for as many connected cameras as possible, what their MAC addresses are (to add to vendor info).

For many cameras (Axis, Y-cam, hikv) they have designated http calls for this info. 

For many, Onvif will do the trick.

We would like to add this functionality to Evercam to discover and save MAC addresses.

@liutingdu looks after discovery and knows a lot about this.

@jgarciasacristan is working on onvif endpoints and might have an opinion on this.

@mosic should see this ticket because it is a good example of a type of ticket and a class of task that he will never have seen before.

**Comment by jgarciasacristan** [comment]
Just back from holidays. Is this ticket a duplication of https://github.com/evercam/evercam-media/issues/10 ?
 As I mentioned in issue #10  I have already covered reading MAC addresses using OnVIF. See the test  "get_network_interfaces method on hikvision camera" in https://github.com/jgarciasacristan/onvifex/blob/master/test/client/device_management_test.exs. Planning to start working over the weekend in the integration of my code with evercam-media so it can be demoed and be of some use.

**Comment by marcoherbst** [comment]
You're totally right. Yes, if you can get that functionality live, then we
can start to use it.
I'm going to edit this ticket to be more about the final step ... of using
the gathered data to update our vendor / model info.

M



On 13 August 2015 at 21:47, jgarciasacristan <notifications@github.com>
wrote:

> Just back from holidays. Is this ticket a duplication of #10
> <https://github.com/evercam/evercam-media/issues/10> ?
> As I mentioned in issue #10
> <https://github.com/evercam/evercam-media/issues/10> I have already
> covered reading MAC addresses using OnVIF. See the test
> "get_network_interfaces method on hikvision camera" in
> https://github.com/jgarciasacristan/onvifex/blob/master/test/client/device_management_test.exs.
> Planning to start working over the weekend in the integration of my code
> with evercam-media so it can be demoed and be of some use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/31#issuecomment-130836365>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by marcoherbst** [comment]
What I imagine here is an admin report to show any MACs that conflict with known vendor model ranges. 
Also, a nice way to edit the vendor data there and then.

**Comment by marcoherbst** [comment]
Report to show all cameras where we know the vendor and we know the MAC ... and MAC lies outside of expected Vendor range.  Report Title = MAC Exceptions.

**Comment by marcoherbst** [comment]
With option: Include cameras where Vendor has no known range.

**Comment by marcoherbst** [comment]
Not really relevant anymore.
