### ISSUE TITLE
Airbrake?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#335]
Do you think we should use Airbrake ? 
https://github.com/romul/airbrake-elixir

It seems to have been useful on API / Dash.

It might also give me insight into deploys:
https://airbrake.io/docs/airbrake-faq/deploy-tracking/

We're paying for it.

We could take this (and other things) off API now?

**Comment by mosic** [comment]
I would expect that we would find it less useful for reporting exceptions `evercam-media` as the code is mostly trying to handle all different cases it can fail (in contrast to using try/catch).

But yes, it might turn out to be nice to have.

**Comment by ijunaidfarooq** [comment]
@marcoherbst What are your suggestion in this area! where should we put Exception handling? 

as When User Sign up? Camera shared? Archive Created? User Deleted? Snapshot endpoints? where can we think of an exception to be raised!

In most cases, we are handling every possible use case.

@mosic and Sir @azharmalik3 I would like your input to this IF we are adding airbrake to media!

**Comment by marcoherbst** [comment]
@ijunaidfarooq  as per Milos' text, if you and he don't see an obvious need for this, then I'm moving it to the long finger.

**Comment by marcoherbst** [comment]
Closing.
