### ISSUE TITLE
Swagger - what to do.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#341]
It was quite nice to have, but not essential. 

If we think we're not going to resurrect it within the next 10 days or so, we should remove links to it from www and dash.

**Comment by marcoherbst** [comment]
@ijunaidfarooq , I think you're the person who has thought most about this. Will you please answer this question with your best judgement. Currently we link to the swagger page from several places, we should either make this work or remove it. I can live with either outcome.

**Comment by ijunaidfarooq** [comment]
In general. 
creating Interactive Documentation is good.

While exploring [apiary](https://help.apiary.io/api_101/api_blueprint_tutorial/ ) Surprisingly on sign up they have the option to create Docs like Swagger but they are in beta version with that . But still, the task is not small so it's better to leave it for now and remove all references of Swagger from the dash.

a way to create it is

![selection_048](https://cloud.githubusercontent.com/assets/13561999/17214718/b1ae40c0-54f3-11e6-9e28-956340f51f28.png)
Its quite way Similar to Swagger, If we go to swagger Editor and By hand Add all these info's and results on publishing will be the very right column. 

for now am putting this Task to long finger as its time taking.

**Comment by marcoherbst** [comment]
Thanks @ijunaidfarooq . Would you mind making the appropriate tasks for Dashboard (Muneeb) & Public Site (Affan) to remove references to Swagger.

**Comment by ijunaidfarooq** [comment]
@marcoherbst Yeah sure :)

**Comment by marcoherbst** [comment]
https://github.com/xerions/phoenix_swagger

**Comment by marcoherbst** [comment]
Duplicate. Closing
