### ISSUE TITLE
Timezones & timestamp: Move to ISO8601 ?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#353]
Related Issues:
https://github.com/evercam/evercam-media/issues/235

**Comment by mosic** [comment]
Currently `evercam-media` mirrors the original implementation in API endpoints. It accepts unix timestamps as the timestamp parameter, and renders them in the same format in json responses. This is not ideal, as we're losing sub-second information which means that we can't save or display more than one snapshot per second. Also in some cases (calendar endpoints) the unix timestamps we accept are offset by the number of seconds in the camera's timezone, which can be really confusing.

Nothing in `evercam-media` architecture or the database is preventing us from fixing this, it's only the API clients which are the problem at the moment. We would first need to change the format that they use for providing timestamps. I suggest using ISO8601 format, with milliseconds and timezone offset (e.g. `2016-07-29T19:12:48.123+01:00`). We would then parse the timestamp in `evercam-media` as `Calendar` `%DateTime{}` struct and pass it around in the app, formatting as a string only when we need to render it.

**Comment by marcoherbst** [comment]
In case it is relevant, this used to be a separate issue, but it feels duplicated:

.... currently when we send a request such as:
https://api.evercam.io/v1/cameras/gpocam/recordings/snapshots?from=1463994000&to=1463997600&limit=3600&

we don't get a response outside of that range ... this is due to how we are converting unix timestamp to deal with timezone ... which kind of defeats the purpose ....

http://michal.muskala.eu/2017/02/02/unix-timestamps-in-elixir-1-4.html

**Comment by marcoherbst** [comment]
Dashboard Work to move to V2 & Cleanup (Azhar 3-4 days) incl. Widgets
Swagger Dashboard work move to V2 (Ali Imran ... 3 days, but keep an open mind about a better way)
Mobile Apps (Nain, 1-2 days?)
Admin - Tell Junaid to use new system
Models Deploy - Evercam Server Side (Azhar work 1 to 1.5 days)
Remove all reference to Motion Detection incl. from API
Remove all code related to "notes" and just return "" value. (We may bring notes back to life later, this is a shortcut so we don't have to make changes in client apps, for now).

**Comment by azharmalik3** [comment]
v1:
{
    "snapshots": [
        {
            "notes": "Evercam Proxy",
            "motion_level": null,
            "created_at": 1549427280
        }
}

v2:
{
    "snapshots": [
        {
            "notes": "Evercam Proxy",
            "motion_level": null,
            "created_at": "2019-02-06T09:28:00+05:00"
        }
}
