### ISSUE TITLE
Foscam / URL Authentication type

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#400]
There are Foscams where you MUST put the U & P in the URL

http://XXXXXXXXXXX/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=user&pwd=pass

We have a couple of these, you can pm me when you want access.

Not sure how RTSP authenticates.

I have a hunch this task might need to be done in 3 steps:
- [ ] Work out how to include this info in the DB/API/VendorModel
- [ ] Do the improvements we plan on making to the VendorModel architecture (a different issue)
- [ ] Make this work on the dashboard etc.

@shankardevy  you're cc'd really because you know about the other auth issues, it may actually not require you here. We'll see.

**Comment by marcoherbst** [comment]
No longer on roadmap
