### ISSUE TITLE
Offer prompts for email / username when creating a new share

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#401]
We had this in Camba, it was nice.

It might require a new endpoint?

GET /cameras/shares/ ?

GET /shares ?

Response:

{ "shared_users": [
{ "email": "liuting+1@evercam.io",
  "

**Comment by marcoherbst** [comment]
How about: 

GET /contacts/ ?

**Comment by ijunaid8088** [comment]
which emails/usernames will be shown in prompt? All the user's or the user's the camera is already been shared or all those user's with whom the acting user has shared any camera.

**Comment by marcoherbst** [comment]
This is something we had, nicely implemented, in Camba.tv. As you type in the email of the sharee, the other sharee's were available.

" all those user's with whom the acting user has shared any camera"

I'm also wondering about the possibility of showing not just the email, but also the full name.  (Yes)

I'm also wondering whether people with whom a camera is shared but not by me are included. (No, if we're using the /contacts analogy)

**Comment by marcoherbst** [comment]
@azharmalik3 before doing this, please explain how you will do this.

**Comment by azharmalik3** [comment]
@marcoherbst 

Route: `v1/users/shares`
It will give a list of all emails according to given api_id and api_key.

**Comment by marcoherbst** [comment]
All emails of what?

All users with whom the current user has shared a camera ?

or

All users with whom the current users' cameras have been shared ? (but not necessarily by that user).

And, I'd be in favour of returning the email & name, no? So that we can make a more beautiful select box (which may also include gravatars & multiple select?)
@azharmalik3

**Comment by azharmalik3** [comment]
All emails mean all users with whom the current users' cameras have been shared.

No issue for me to return email and name. That's a good idea to use multiple select.

**Comment by marcoherbst** [comment]
Ok, good, let's do it that way. Good.

**Comment by azharmalik3** [comment]
Created an endpoint to get /shared/users and display in camera share form.

Leave multiple camera shares because have some complications to validate params first then create share / share-request for each email.
