### ISSUE TITLE
Improve Rights?

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#405]
In camera object there is a field called "rights", it's a comma separated list of the user's rights on the camera, here are some examples:
- Camera that I own:  
  `"rights": "snapshot,view,edit,delete,list,grant~snapshot,grant~view,grant~edit,grant~delete,grant~list"`
- Camera shared with me with "Read Only":  
  `"rights": "snapshot,list"`
- Camera shared with me with "Full Rights":  
  `"rights": "snapshot,view,edit,list,grant~snapshot,grant~view,grant~edit,grant~list"`

I didn't see any other use cases so far but there is an issue #435 that the shared cameras have unusual rights string.

From the Android app:
- If I want to delete a camera, I need to check if the "rights" string contains "delete". 
- If I want to edit the camera, I need to check if the "rights" string contains "edit". 
- If I want to know if the camera has full rights or not, I am checking if the string equals `"snapshot,view,edit,list,grant~snapshot,grant~view,grant~edit,grant~list"`

There is no documents explain what's the right way to check rights so I was doing all things above based on my guessing.. @azharmalik3  @mosic Please correct me if anything is incorrect.

I am not sure what is the best way to handle user rights on the API side, I am creating this issue from the client side point of view as an open question..

**Comment by marcoherbst** [comment]
Inspiration:
![image](https://cloud.githubusercontent.com/assets/5648894/21845718/a4a508de-d7eb-11e6-8acc-6bf26cd310e0.png)

**Comment by marcoherbst** [comment]
This is kind of working at the moment, I will close.
