### ISSUE TITLE
Ability to add an Onvif camera

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#406]
Vendor: OnVIF 
Model: Default

This is what I think: (not sure):

This endpoint will work differently to others as there is no such thing as a standard jpeg or h264 URL.
Instead, the inputs will be External IP, Port, U&P (optional) and the endpoint will query the camera using the appropriate OnVIF commands to determine the media URLs and will add the camera with these.

**Comment by marcoherbst** [comment]
Vendor: OnVIF 
Model: Default

**Comment by marcoherbst** [comment]
@ijunaid8088 if you're thinking of tackling this, then first please explain in detail in the comments how you plan to tackle it.

**Comment by ijunaid8088** [comment]
I think It will work the same way as we did for Getting Mac Address for camera, Every other process is same for adding the camera but  we are sending command to camera for giving us Mac Address, 

Now every other process will be same but if the vendor is Onvif then we will send commands to get media URLs and then add/update them to camera while adding.

**Comment by ijunaid8088** [comment]
as I discussed it with Sir @azharmalik3 We are going to create a new Vendor Onvif.

And when user will select that Vendor and Mode default, then we are only going to ask for External IP, Port and credentials (optional), the other form for Add IP Camera will not be visible to user. And when User will Add the camera, We will send an Onvif request to get all the available data for the camera and add it.

we can get Snapshot Urls by onvif commands using Media service, http://www.onvif.org/ver20/media/wsdl/media.wsdl

**Comment by ijunaid8088** [comment]
So far I came to this conclusion about this:

After getting IP and Port, there are going to be 2 services and 5 operations which are going to be called from dashboard to evercam server to get the details about the camera as mentioned in the drawing.

with these details, the camera is going to be added. Moreover adding the new model to DB will be a separate.. in case User wanted to add it to DB or not.  
https://docs.google.com/drawings/d/1a07Ffq5rTRX8BEZiU398zMhBCiPWL7sfe515HcH7sZU/edit?usp=sharing

**Comment by ijunaid8088** [comment]
We are on right path regarding this but still not sure about this yet. So I am moving this to future milestone.

**Comment by marcoherbst** [comment]
No longer relevant
