### ISSUE TITLE
Remove all references to the duplicated storage of URLS (json) in Vendors & Models.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#407]
@azharmalik3 thinks ~ 1 day and will effect all codebases (dash server models admin)

**Comment by azharmalik3** [comment]
@marcoherbst 1st and 2nd points already completed and deployed. 

And P3 is still pending and it's a big change.

**Comment by azharmalik3** [comment]
Removed duplicate fields and all references.
