### ISSUE TITLE
Make use of different auth types (digest & cookie) in /models/:model-id

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#408]
This is the final part of fixing evercam/evercam-media#5 and evercam/evercam-media#6

It will also mean undoing the fallback code that will have been written in evercam-media

**Comment by marcoherbst** [comment]
@azharmalik3 how do you think this should be done?
I think the question is that you currently are hardcoding basic/digest and we need to decide whether to implement this on a per Model or per Camera basis, right?
Do you have a preference?

**Comment by azharmalik3** [comment]
Implemented auth on a model basis.

Think about the camera basis auth but found more suited to implement on the model side instead of the camera.
