### ISSUE TITLE
Recording Deletion changes (Suggestion Only)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#412]
When one changes the recording duration, only change it for future recordings.

**Comment by marcoherbst** [comment]
@azharmalik3 I think this issue is not a Timelapse issue, right, it's a Cloud Recording issue, and p2 is completed , yes?

**Comment by azharmalik3** [comment]
Yes, it's not a timelapse issue.

Yes, p2 is completed.

**Comment by marcoherbst** [comment]
Doesn't make sense to me anymore.
