### ISSUE TITLE
See some repeating users in admin

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-server#417]
we see some repeating user in admin panel, when i try to trace the users from intercom, there is no record from where these users created, means i was trying to get information from which platform these users are creating iOS or Android but no trace on intercom. I need your suggestion, that what can be possible error, because there is no error on mobile devices.

**Comment by azharmalik3** [comment]
Investigated this issue. Tested dashboard and apps sign up flow. Also, looked into Heroku log entries and Sumologic logs. Found that these users were not created by dashboard or apps. Also, noticed that 15 to 20 cameras created in 1hr. @marcoherbst I think we should pass a unique token to avoid spam requests.

**Comment by azharmalik3** [comment]
Here are some repeating users.
![pasted image at 2016_10_06 02_39 pm](https://cloud.githubusercontent.com/assets/6176136/19147991/2fdfce84-8bd4-11e6-8604-248f09f0cbbc.png)

**Comment by marcoherbst** [comment]
We see no pattern to this. I consider it unsolved, but will push it into the future.

**Comment by azharmalik3** [comment]
It's already done.

**Comment by marcoherbst** [comment]
Would you check there is a similar issue  in dashboard, is it now also
solved? Maybe it is intercom related

M
