### ISSUE TITLE
Email validation not working on user creation

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-server#425]
A user was created with an irregular email, through android and no error was given from media.

**Comment by muneeb2542** [comment]
a new user was created with an email of "muneeb@.gmail" from android,

It should have been revoked on sign up by media but in fact, it was successfully created and was redirected to the index page.

**Comment by ijunaidfarooq** [comment]
@muneeb2542

**Comment by marcoherbst** [comment]
The only thing that matters here is that we pick a regex and apply it across the entire codebase & make it clear in the Wiki which one we're using so that this vampire can finally be killed. 

NB. Don't get hung up on which regex, none are perfect. Choose one.
