### ISSUE TITLE
Resize the thumbnail used in thumbnail_url camera attribute

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#46]
@liutingdu If you have any comments now would be a good time to add them :)

I think using 640px width would be okay here?

**Comment by marcoherbst** [comment]
NB. These Thumbnails are NOT live. 

Let us ONLY have Thumnails (640*480 max dimensions) and Toenails (64*64 max dimensions) generated on POST / PATCH of camera.

Does that help?

**Comment by mosic** [comment]
Yeah, I just made an issue on `evercam-api` to add the toenail url to the camera: https://github.com/evercam/evercam-api/issues/421

**Comment by marcoherbst** [comment]
From @shankardevy 

Lambda looks interesting but it's something none of us have a good experience. We could take it up as a trial but I also question myself why we should take these steps for simple things like thumbnail generation what we need dynamically and don't have to store it anywhere?

Why not an endpoint in media.evercam.io, say, camera/:id/thumbnail or camera/:id/toenail

that does the resizing using https://github.com/route/mogrify and return it? 

This resizing could be done on the same node to start with and then lateron we could also delegate the resizing to a new ec2 that connects with media.evercam.io and does only the image processing

**Comment by marcoherbst** [comment]
Closing, duplicated: https://github.com/evercam/evercam-server/issues/100
