### ISSUE TITLE
Show & Tell Pizza

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#461]
Big subjects about which we need to actively share info across the team.
10 minute sessions using Google Slides.
1-2 hrs preparation (approx). (i.e. These are light overviews, not deep dives)
Friday 3pm Local Time.

Week 1: (Done)
- [x] ffmpeg Introduction @azharmalik3 
- [x] Firebase Introduction @Zulqarnain-Mustafa 
       https://scotch.io/bar-talk/a-look-at-the-new-firebase-a-powerful-google-platform

Week 2: (Thurday 24th November)
- [x] Storage in Evercam: SeaweedFS ( Haystack etc. ) , alternatives ... @ijunaidfarooq ( 26/09 )
- [x] RTSP , RTMP , HLS , h264, h265, mjpeg, mp4  ...  @azharmalik3  
http://www.axis.com/ro/en/learning/web-articles/technical-guide-to-network-video/video-compression-guide
http://www.informit.com/articles/article.aspx?p=169578&seqNum=3 

Week 3 (Friday 30th December)
- [x] Billing / Stripe @muneeb2542 

Week 4 (Friday 9th December)
- [x] OnVIF , what it is and how Evercam Uses it. @ijunaid8088 or @Zulqarnain-Mustafa 
http://www.hikvisioneurope.com/portal/index.php?dir=Integration%20and%20Development%20Materials/03--Protocol/00--ONVIF%20v2.4/ 
https://github.com/evercam/evercam-server/wiki/Onvif-support-in-evercammedia

Week 5 (Friday 6th January)
- [x] @Zulqarnain-Mustafa Deep Linking & App indexing.
https://www.youtube.com/watch?v=pl1-m8tJDmQ

Week 6 (Friday 30th December)
- [x] Install a camera and connect to Evercam, from scratch. @faisal2472 

Week 7 (Friday 20th January)
- [x] IPVM Camera Calculator @faisal2472 

Week 8 and Week 9 were both a miss for Show and tell.

Week 10 (Friday 10th February)
- [x] Youtube live streamer / CamStreamer walk through @faisal2472 (Not fully but partially )

week 11 (Friday 17th February)
- [x] SEO (Google Analytics, Yoast, Webmaster Tools, others...) @affan00 

week 13 (Thursday 16th March)
- [x] Company Business Plan 2017 @marcoherbst

week 15 (Friday 31st March)
- [x] Camera Workers @azharmalik3  
       https://github.com/evercam/evercam-server/wiki/Media:-camera-workers

week 16 (Friday 7th April)
- [x] pick some other cctv software & do a review & feature comparison @faisal2472 

week 17 (Friday 14th April)
- [ ] SumoLogic, Logs, Monitoring @ijunaid8088  @azharmalik3

Future:

- [ ] CUDA / OpenCL
- [ ] RAID @ijunaidfarooq 
- [ ] Erlang Nodes & OTP https://www.parallella.org/2013/09/10/explorations-in-erlang-with-the-parallella-playing-with-pixels/ @ijunaid8088 @azharmalik3 
- [ ] SNMP, Nagios, Erlang SNMP, Online/Offline, Uptime Robot, Ping.Apex.sh @ijunaidfarooq 
- [ ] Javascript Frameworks e.g. AngularJS , Ember, React  @affan00

**Comment by marcoherbst** [comment]
@ijunaidfarooq  @azharmalik3 @Zulqarnain-Mustafa  .... which one first? 

This Friday ?

**Comment by ijunaid8088** [comment]
Tomorrow's plan : 
as everyone is okay with that..
Install a camera and connect to Evercam, from scratch. @faisal2472

**Comment by marcoherbst** [comment]
@ijunaid8088 did that happen? if so, what's next? and please could you update / fix the dates etc. in the description above.

**Comment by ijunaid8088** [comment]
@marcoherbst No last time, everybody has so much to do in the timeline, Today we are doing this.

**Comment by ijunaid8088** [comment]
@affan00 Get ready for your turn.. :)

**Comment by marcoherbst** [comment]
I'm closing this. 

@affan00 @azharmalik3 @ijunaid8989 @Ali7862 

You get the idea. Talk more. :)
