### ISSUE TITLE
For test snapshot proper json is not returning as other end points returns 

### ISSUE THREAD

**Issue by Zulqarnain-Mustafa** [evercam/evercam-server#475]
Test SnapShot Error response:
{"response":"<?xml version=\"1.0\" encoding=\"iso-8859-1\"?>\n<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional\/\/EN\"\n         \"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transitional.dtd\">\n<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\" xml:lang=\"en\" lang=\"en\">\n <head>\n  <title>404 - Not Found<\/title>\n <\/head>\n <body>\n  <h1>404 - Not Found<\/h1>\n <\/body>\n<\/html>\n","message":"Camera snapshot url is not found."}

**Comment by marcoherbst** [comment]
@azharmalik3  suggestions ?

**Comment by marcoherbst** [comment]
@azharmalik3 's suggestion is to return the error code, not the text from the camera. (in this case, that's a 404).

Sometimes, there will be 200 Success responses that return errros, such as:

<ResponseStatus xmlns="http://www.isapi.org/ver20/XMLSchema" version="2.0">
<requestURL>/ISAPI/Streaming/channels/5012/picture</requestURL>
<statusCode>3</statusCode>
<statusString>Device Error</statusString>
<subStatusCode>deviceError</subStatusCode>
</ResponseStatus>

... these need to be parsed like we do here:
https://github.com/evercam/evercam-media/blob/master/lib/evercam_media/snapshot/error.ex#L24

**Comment by ijunaid8088** [comment]
@Zulqarnain-Mustafa Please put some more information about this. I was unable to reproduce this case

**Comment by Zulqarnain-Mustafa** [comment]
Seems like fixed now:
`{
    message = "Camera responded with a Forbidden message.";
    response = "<HTML><HEAD><TITLE>403 Forbidden</TITLE></HEAD>\n<BODY><H1>403 Forbidden</H1>\nYour client does not have permission to get URL /axis-cgi/jpg from this server.\n</BODY></HTML>\n";
}`

Now it has message key. which we are using in our applications.
