### ISSUE TITLE
Create endpoints for forgotten password.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#476]
Forget password request endpoint:
Route: `POST v1/users/:email/password/reset`
params: `email`
Forget request will send an email to user with `token` and this token will be used to update token.

Route: `PATCH v1/users/:email/password`
params: `email, new-password, token`

**Comment by marcoherbst** [comment]
@ijunaidfarooq  not sure why you added this to current milestone. I'm removing it.

**Comment by marcoherbst** [comment]
Reassigned. This can be done by the first person who feels ready for it. Nice toe-dipper.

**Comment by azharmalik3** [comment]
Endpoints completed for a forgotten password.
