### ISSUE TITLE
update :erlware_commons

### ISSUE THREAD

**Issue by ijunaid8088** [evercam/evercam-server#484]
as for now in mix.exs file 

```
{:relx, github: "erlware/relx", override: true}, # <-- depends on erlware_commons-0.18.0
{:erlware_commons, "~> 0.19.0", override: true}, # <-- @0.18.0 right now
```

as I tried to update `erlware_commons` I started getting `rebar` errors

**Comment by ijunaidfarooq** [comment]
Dependency not available: erlware_commons-0.19.0 (undefined)
Dependency not available: cf-0.2.1 (undefined)
ERROR: compile failed while processing /home/ijunaidfarooq/evercam/evercam-media/deps/relx: rebar_abort
==> evercam_media
** (Mix) Could not compile dependency :relx, "/home/ijunaidfarooq/.mix/rebar compile skip_deps=true deps_dir="/home/ijunaidfarooq/evercam/evercam-media/_build/dev/lib"" command failed. You can recompile this dependency with "mix deps.compile relx", update it with "mix deps.update relx" or clean it with "mix deps.clean relx"

**Comment by marcoherbst** [comment]
@ijunaidfarooq  related ? https://github.com/bitwalker/exrm/issues/294

**Comment by ijunaid8088** [comment]
Done and fixed https://github.com/evercam/evercam-server/pull/573.
