### ISSUE TITLE
Auto throttle speed of requests based on individual camera performance

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#487]
Proposed solution:
Then we should increase the max request rate (by 0.2 secs) until we get less than 3 time outs per 10 seconds. We can then, when we begin to get 0 time outs per 60 mins, to reduce the max request rate by 0.05 seconds.

**Comment by marcoherbst** [comment]
Useful for scenarios where camera begins to generate busy errors.

**Comment by marcoherbst** [comment]
Camera sometimes returns images, but often times out

Proposed solution:
Then we should increase the max request rate (by 0.2 secs) until we get less than 3 time outs per 10 seconds. We can then, when we begin to get 0 time outs per 60 mins, to reduce the max request rate by 0.05 seconds. @shankardevy

**Comment by marcoherbst** [comment]
Covered in https://github.com/evercam/evercam-server/issues/853
