### ISSUE TITLE
share object is nil for "Herbst Wicklow Cam" even though it shouldn't be

### ISSUE THREAD

**Issue by muneeb2542** [evercam/evercam-server#519]
Herbst Wicklow Cam is a camera that is already shared to an account when it is created.The share object is used in differentiating between owned and not owned cameras but share object is nil for this camera that is why even though it is already added to account we can still see "add to my cameras" notice on the live view of it.

**Comment by marcoherbst** [comment]
I've 2 problems with this:

1. Why is share object being used to differentiate between owned and not owned. I thought we had an owner field for that? @muneeb2542  I see not info about where you were encountering this problem.

2. I'm pretty sure this "bug" was deliberate as the #users is so large (and only relevant to a full-rights sharee) that we return a null to keep things moving smoothly.

**Comment by azharmalik3** [comment]
Actually, we returned empty shares for default shared camera `evercam-remembrance-camera` that's why it returns empty. So I added a check in condition if user requests share with a specific `user_id` then return share instead of empty.

Now issues fixed.
