### ISSUE TITLE
Cloud Recordings: Pause Function

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#531]
New Status: Paused, which keeps current recordings.

The /cameras-report should display as:
30 Days (On Schedule)
7 Days (Continuous)
Off (No Recordings)
Paused (7 Days)

If CR status = "null" , should we show default values for frequency etc. ?

Notice if resuming recordings after more than 24hrs:

"Your recordings were paused 3 days ago. If you resume recording ( 7 days )  then 3 days of your footage will be lost. Are you sure you want to continue,   YES   |  NO"

**Comment by marcoherbst** [comment]
@azharmalik3  ... I've updated this issue. Do you still think it contains unanswered questiosn? Or is it now well enough specified and do you agree with it?

**Comment by azharmalik3** [comment]
@marcoherbst 30 Days (Scheduled)? You mean 30 days always on-schedule recording?

I think it can be either on-schedule or continuous.

**Comment by marcoherbst** [comment]
Yes. (edited)

**Comment by azharmalik3** [comment]
Will we remove 90 days and infinity option?

**Comment by azharmalik3** [comment]
Done.
