### ISSUE TITLE
Add all routes to evercam docs

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#558]
Enlist all endpoints currently being used in evercam-media to http://docs.evercam.io/

**Comment by marcoherbst** [comment]
Could this be implemented as a feature within https://github.com/elixir-lang/ex_doc ?

**Comment by marcoherbst** [comment]
@ijunaid8989  is this a thing? what's your current thought?

**Comment by marcoherbst** [comment]
@ijunaid8989 is this still a thing? Are there tasks around documentation that would make life easier for others e.g. @elyas20  or @JaviCT  (Who will at some point want to spend more time inside Server code).

If yes, please try to describe and estimate the work required.

**Comment by ijunaid8989** [comment]
We have done Swagger docs, already and when we started it, the purpose of `docs.evercam.io` was to create **https://hexdocs.pm**, for evercam-server. but then we left this idea because our codebase is not in use of anyone else but us. So I am closing this.
