### ISSUE TITLE
Deal with cameras that have Z, but not P&T e.g. hik-demo

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#56]
This will mean changing how we store make/model data ... and more.
M

**Comment by jgarciasacristan** [comment]
@marcoherbst  Can you share this camera with me. I would like to test Onvif commands on this one. I suppose zoom should work.

**Comment by mosic** [comment]
@jgarciasacristan I just shared it with you, so you don't have to wait for the response tomorrow.

**Comment by jgarciasacristan** [comment]
Thanks. I'll play with it tonight.

**Comment by jgarciasacristan** [comment]
ONVIF Profile of HIKDemo camera does not support PTZ:
 `%{"AudioEncoderConfiguration" => %{"Bitrate" => "64", "Encoding" => "G711", "Multicast" => %{"Address" => %{"IPv4Address" => "0.0.0.0", "Type" => "IPv4"}, "AutoStart" => "false", "Port" => "8600", "TTL" => "1"}, "Name" => "AudioEncoderConfig", "SampleRate" => "8", "SessionTimeout" => "PT5S", "UseCount" => "3", "token" => "MainAudioEncoderToken"}, "AudioSourceConfiguration" => %{"Name" => "AudioSourceConfig", "SourceToken" => "AudioSourceChannel", "UseCount" => "3", "token" => "AudioSourceConfigToken"}, "Extension" => %{"AudioDecoderConfiguration" => %{"Name" => "AudioDecoderConfig", "UseCount" => "3", "token" => "AudioDecoderConfigToken"}, "AudioOutputConfiguration" => %{"Name" => "AudioOutputConfigName", "OutputLevel" => "10", "OutputToken" => "AudioOutputToken", "SendPrimacy" => "www.onvif.org/ver20/HalfDuplex/Server", "UseCount" => "3", "token" => "AudioOutputConfigToken"}}, "Name" => "mainStream", "VideoAnalyticsConfiguration" => %{"AnalyticsEngineConfiguration" => %{"AnalyticsModule" => [%{"Name" => "MyCellMotionModule", "Parameters" => %{"ElementItem" => %{"CellLayout" => %{"Columns" => "22", "Rows" => "18", "Transformation" => %{"Scale" => %{"x" => "0.090909", "y" => "0.111111"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, "Name" => "Layout"}, "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "0"}}, "Type" => "tt:CellMotionEngine"}, %{"Name" => "MyLineDetectorModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "50"}}, "Type" => "tt:LineDetectorEngine"}, %{"Name" => "MyFieldDetectorModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "50"}}, "Type" => "tt:FieldDetectorEngine"}, %{"Name" => "MyTamperDetecModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Transformation", "Transformation" => %{"Scale" => %{"x" => "0.002841", "y" => "0.003472"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "576"}, %{"x" => "704", "y" => "576"}, %{"x" => "704", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "0"}}, "Type" => "hikxsd:TamperEngine"}, %{"Name" => "MyCountAggregationModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "50"}}, "Type" => "tt:CountAggregationEngine"}]}, "Name" => "VideoAnalyticsName", "RuleEngineConfiguration" => %{"Rule" => [%{"Name" => "MyMotionDetectorRule", "Parameters" => %{"SimpleItem" => [%{"Name" => "MinCount", "Value" => "5"}, %{"Name" => "AlarmOnDelay", "Value" => "1000"}, %{"Name" => "AlarmOffDelay", "Value" => "1000"}, %{"Name" => "ActiveCells", "Value" => "0P8A8A=="}]}, "Type" => "tt:CellMotionDetector"}, %{"Name" => "MyLineDetector1", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "670.000000", "y" => "790.000000"}, %{"x" => "477.000000", "y" => "702.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector2", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "1000.000000"}, %{"x" => "0.000000", "y" => "1000.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector3", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "1000.000000"}, %{"x" => "0.000000", "y" => "1000.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector4", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "1000.000000"}, %{"x" => "0.000000", "y" => "1000.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyFieldDetector1", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector2", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector3", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector4", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyTamperDetectorRule", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}]}}}}, "Type" => "hikxsd:TamperDetector"}, %{"Name" => "MyCountAggregation1", "Parameters" => %{"ElementItem" => %{"Name" => "LineSegments", "PolylineArrayConfiguration" => %{"PolylineArray" => %{"Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}}, "SimpleItem" => [%{"Name" => "ReportTimeInterval", "Value" => "PT15M"}, %{"Name" => "ResetTimeInterval", "Value" => "PT30M"}, %{"Name" => "Direction", "Value" => "Right"}]}, "Type" => "tt:CountAggregation"}]}, "UseCount" => "3", "token" => "VideoAnalyticsToken"}, "VideoEncoderConfiguration" => %{"Encoding" => "H264", "H264" => %{"GovLength" => "50", "H264Profile" => "High"}, "Multicast" => %{"Address" => %{"IPv4Address" => "0.0.0.0", "Type" => "IPv4"}, "AutoStart" => "false", "Port" => "8600", "TTL" => "1"}, "Name" => "VideoEncoder_1", "Quality" => "3.000000", "RateControl" => %{"BitrateLimit" => "4096", "EncodingInterval" => "1", "FrameRateLimit" => "8"}, "Resolution" => %{"Height" => "1080", "Width" => "1920"}, "SessionTimeout" => "PT5S", "UseCount" => "1", "token" => "VideoEncoderToken_1"}, "VideoSourceConfiguration" => %{"Bounds" => %{"height" => "1080", "width" => "1920", "x" => "0", "y" => "0"}, "Extension" => %{"Rotate" => %{"Mode" => "OFF"}}, "Name" => "VideoSourceConfig", "SourceToken" => "VideoSource_1", "UseCount" => "3", "token" => "VideoSourceToken"}, "fixed" => "true", "token" => "Profile_1"}`

Here is a PTZ compliant profile from the MobileMast camera. Look for PTZConfiguration:
`%{"AudioEncoderConfiguration" => %{"Bitrate" => "64", "Encoding" => "G711", "Multicast" => %{"Address" => %{"IPv4Address" => "0.0.0.0", "Type" => "IPv4"}, "AutoStart" => "false", "Port" => "8600", "TTL" => "1"}, "Name" => "AudioEncoderConfig", "SampleRate" => "8", "SessionTimeout" => "PT5S", "UseCount" => "3", "token" => "MainAudioEncoderToken"}, "AudioSourceConfiguration" => %{"Name" => "AudioSourceConfig", "SourceToken" => "AudioSourceChannel1", "UseCount" => "3", "token" => "AudioSourceConfigToken"}, "Extension" => %{"AudioDecoderConfiguration" => %{"Name" => "AudioDecoderConfig", "UseCount" => "3", "token" => "AudioDecoderConfigToken"}, "AudioOutputConfiguration" => %{"Name" => "AudioOutputConfigName", "OutputLevel" => "10", "OutputToken" => "AudioOutputToken", "SendPrimacy" => "www.onvif.org/ver20/HalfDuplex/Server", "UseCount" => "3", "token" => "AudioOutputConfigToken"}}, "Name" => "mainStream", "PTZConfiguration" => %{"DefaultAbsolutePantTiltPositionSpace" => "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace", "DefaultAbsoluteZoomPositionSpace" => "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace", "DefaultContinuousPanTiltVelocitySpace" => "http://www.onvif.org/ver10/tptz/PanTiltSpaces/VelocityGenericSpace", "DefaultContinuousZoomVelocitySpace" => "http://www.onvif.org/ver10/tptz/ZoomSpaces/VelocityGenericSpace", "DefaultPTZSpeed" => %{"PanTilt" => %{"space" => "http://www.onvif.org/ver10/tptz/PanTiltSpaces/GenericSpeedSpace", "x" => "0.100000", "y" => "0.100000"}, "Zoom" => %{"space" => "http://www.onvif.org/ver10/tptz/ZoomSpaces/ZoomGenericSpeedSpace", "x" => "1.000000"}}, "DefaultPTZTimeout" => "PT300S", "DefaultRelativePanTiltTranslationSpace" => "http://www.onvif.org/ver10/tptz/PanTiltSpaces/TranslationGenericSpace", "DefaultRelativeZoomTranslationSpace" => "http://www.onvif.org/ver10/tptz/ZoomSpaces/TranslationGenericSpace", "Name" => "PTZ", "NodeToken" => "PTZNODETOKEN", "PanTiltLimits" => %{"Range" => %{"URI" => "http://www.onvif.org/ver10/tptz/PanTiltSpaces/PositionGenericSpace", "XRange" => %{"Max" => "1.000000", "Min" => "-1.000000"}, "YRange" => %{"Max" => "1.000000", "Min" => "-1.000000"}}}, "UseCount" => "3", "ZoomLimits" => %{"Range" => %{"URI" => "http://www.onvif.org/ver10/tptz/ZoomSpaces/PositionGenericSpace", "XRange" => %{"Max" => "1.000000", "Min" => "0.000000"}}}, "token" => "PTZToken"}, "VideoAnalyticsConfiguration" => %{"AnalyticsEngineConfiguration" => %{"AnalyticsModule" => [%{"Name" => "MyCellMotionModule", "Parameters" => %{"ElementItem" => %{"CellLayout" => %{"Columns" => "22", "Rows" => "18", "Transformation" => %{"Scale" => %{"x" => "0.090909", "y" => "0.111111"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, "Name" => "Layout"}, "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "0"}}, "Type" => "tt:CellMotionEngine"}, %{"Name" => "MyLineDetectorModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "50"}}, "Type" => "tt:LineDetectorEngine"}, %{"Name" => "MyFieldDetectorModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "50"}}, "Type" => "tt:FieldDetectorEngine"}, %{"Name" => "MyTamperDetecModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Transformation", "Transformation" => %{"Scale" => %{"x" => "0.002841", "y" => "0.003472"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "576"}, %{"x" => "704", "y" => "576"}, %{"x" => "704", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "0"}}, "Type" => "hikxsd:TamperEngine"}, %{"Name" => "MyLoiteringDetectorModule", "Parameters" => %{"ElementItem" => [%{"Name" => "Layout", "Transformation" => %{"Scale" => %{"x" => "0.002000", "y" => "0.002000"}, "Translate" => %{"x" => "-1.000000", "y" => "-1.000000"}}}, %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "1000"}, %{"x" => "1000", "y" => "1000"}, %{"x" => "1000", "y" => "0"}]}}}], "SimpleItem" => %{"Name" => "Sensitivity", "Value" => "1225"}}, "Type" => "tt:LoiteringDetectorEngine"}]}, "Name" => "VideoAnalyticsName", "RuleEngineConfiguration" => %{"Rule" => [%{"Name" => "MyMotionDetectorRule", "Parameters" => %{"SimpleItem" => [%{"Name" => "MinCount", "Value" => "5"}, %{"Name" => "AlarmOnDelay", "Value" => "1000"}, %{"Name" => "AlarmOffDelay", "Value" => "1000"}, %{"Name" => "ActiveCells", "Value" => "zwA="}]}, "Type" => "tt:CellMotionDetector"}, %{"Name" => "MyLineDetector1", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector2", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector3", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyLineDetector4", "Parameters" => %{"ElementItem" => %{"Name" => "Segments", "Polyline" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}, "SimpleItem" => %{"Name" => "Direction", "Value" => "Any"}}, "Type" => "tt:LineDetector"}, %{"Name" => "MyFieldDetector1", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector2", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector3", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyFieldDetector4", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "Type" => "tt:FieldDetector"}, %{"Name" => "MyTamperDetectorRule", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}, %{"x" => "0", "y" => "0"}]}}}}, "Type" => "hikxsd:TamperDetector"}, %{"Name" => "MyLoiteringDetector1", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector2", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector3", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector4", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector5", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector6", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector7", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}, %{"Name" => "MyLoiteringDetector8", "Parameters" => %{"ElementItem" => %{"Name" => "Field", "PolygonConfiguration" => %{"Polygon" => %{"Point" => [%{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}, %{"x" => "0.000000", "y" => "0.000000"}]}}}, "SimpleItem" => [%{"Name" => "TimeThreshold", "Value" => "0"}, %{"Name" => "doPeriodicNotify", "Value" => "false"}, %{"Name" => "TimeInterval", "Value" => "PT5S"}]}, "Type" => "tt:LoiteringDetector"}]}, "UseCount" => "3", "token" => "VideoAnalyticsToken"}, "VideoEncoderConfiguration" => %{"Encoding" => "H264", "H264" => %{"GovLength" => "25", "H264Profile" => "High"}, "Multicast" => %{"Address" => %{"IPv4Address" => "0.0.0.0", "Type" => "IPv4"}, "AutoStart" => "false", "Port" => "8600", "TTL" => "1"}, "Name" => "VideoEncoder_1", "Quality" => "3.000000", "RateControl" => %{"BitrateLimit" => "4096", "EncodingInterval" => "1", "FrameRateLimit" => "25"}, "Resolution" => %{"Height" => "1080", "Width" => "1920"}, "SessionTimeout" => "PT5S", "UseCount" => "1", "token" => "VideoEncoderToken_1"}, "VideoSourceConfiguration" => %{"Bounds" => %{"height" => "1080", "width" => "1920", "x" => "0", "y" => "0"}, "Name" => "VideoSourceConfig", "SourceToken" => "VideoSource_1", "UseCount" => "3", "token" => "VideoSourceToken"}, "fixed" => "true", "token" => "Profile_1"}`

When I invoke PTZ commands on the HIK Demo camera I got error 500 PTZ not supported (as expected). 
`<env:Reason><env:Text xml:lang=\"en\">PTZ is not supported..</env:Text>\r\n</env:Reason>\r\n<env:Node>http://www.w3.org/2003/05/soap-envelope/node/ultimateReceiver</env:Node>\r\n<env:Role>http://www.w3.org/2003/05/soap-envelope/role/ultimateReceiver</env:Role>\r\n<env:Detail><env:Text>PTZ is not supported by the device.</env:Text>`

I wonder how zoom works when used from the camera UI. I don't think it uses ONVIF for it.

**Comment by marcoherbst** [comment]
Closing this, it's no longer on the roadmap.
