### ISSUE TITLE
APIMetrics Config

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#563]
- [x]  Change reports to London Only
- [x]  Add more weed endpoints
- [x]  Add server endpoints
- [x]  For weed endpoints, create workflows & alerts to trigger alarms. ( OK 200 isn't adequate )
- [x]  For latency significantly above average trigger alarms (like, say 50% more than average london ms)
- [x] Create single report with all endpoints for latency graph.

NB, London, 10 min interval is fine.

**Comment by ijunaid8088** [comment]
![image](https://cloud.githubusercontent.com/assets/13561999/20741970/44d8e92e-b6ef-11e6-91e1-29d454dc856c.png)
