### ISSUE TITLE
Create Staging Server

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#569]
.... and see if evercam-server can be moved onto it's own Hetzner vServer. Would be good if it could.

Consider how we want an Elastic IP. Not easy.

**Comment by marcoherbst** [comment]
@azharmalik3 , if this is closed, then feel free to close it. The elastic IP & relocation of evercam-server are separate issues.

**Comment by azharmalik3** [comment]
Staging server created.
