### ISSUE TITLE
update last login time ...

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#571]
or not?

if we want this?

https://github.com/evercam/evercam-ios/issues/138

**Comment by ijunaid8088** [comment]
In past, I had a memory of a long discussion on this issue regarding https://github.com/evercam/evercam-server/issues/298 and us,, at the end closed it.

**Comment by marcoherbst** [comment]
@ijunaid8088 , I think the decision is binary:

1. We care about last login date / time and keep this date accurate , possibly by updating it with every client request.

Or.

2. We don't care about this date and remove it across our system. (after all, we get the same thing from intercom).

Your vote, @ijunaid8088 ?

**Comment by azharmalik3** [comment]
@marcoherbst I think we should update the last login in /credentials endpoint because we are using this endpoint for logging in apps.

**Comment by azharmalik3** [comment]
Done.
