### ISSUE TITLE
Camera comes online more than it goes offline.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#572]
For example:

![image](https://cloud.githubusercontent.com/assets/5648894/20701988/b50d78aa-b60d-11e6-8051-2df38a7591e7.png)

https://dash.evercam.io/v1/cameras/bennett-dorset/logs

**Comment by azharmalik3** [comment]
Not able to replicate this issue so moving this issue in the long finger and will look into this another day.

**Comment by marcoherbst** [comment]
I'm closing this as it is being dealt with now by @ijunaid8989
