### ISSUE TITLE
Notifications: [ ] Send me a notification if this camera goes offline ( my@email.com )

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#578]
> [  ] Send me a notification if this camera goes offline.

This is to replace the flag in the camera object of "Send owner notification"

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-android/issues/77

**Comment by marcoherbst** [comment]
Some questions:
This could be stored as a list of emails within the camera object.
If we do it that way, then there is no new endpoint, but it would seem to be then correct to change the UX to enable multiple editing of emails. (as it was in camba.tv).
Slight concern is that subscribing / unsubscribing to notifications should really be a choice for an individual user, rather than for a full-rights user to do on behalf of other users.
Consider the read-only user. They should be able to do it for themselves, but not for others.

**Comment by azharmalik3** [comment]
Now camera owner and full rights shared user can enable/disable `Send me offline notification` option.
