### ISSUE TITLE
Cosmetic Changes to Camera Shared Email

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#579]
1. It should not strip line breaks. (But do worry about SQL injection type attacks).
2. Subject: Vinnie Quinn has shared the camera Stewart Harcourt with you.
3. Then go straight to "Vinnie's Message for you" with the message in the grey box.
4. Instead of the URL, have a nice button "Create your account & access your camera"
5. Footer stays the same, I've emailed a rough sample to @azharmalik3 who can reassign as he wishes.

**Comment by azharmalik3** [comment]
Done.
