### ISSUE TITLE
Elixir to 1.4

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#598]
* Erlang 19
* Elixir 1.4

**Comment by azharmalik3** [comment]
@marcoherbst 

Updated Elixir version to 1.4.1 and fixed all possible warnings but we are using some dependencies (credo, exrm, porcelain and quantum) which are still on older version of elixir. So, we can't solve those warnings until they upgrade their dependencies to new elixir version.

If everything works fine then we can live with these warnings. But it needs testing.

**Comment by azharmalik3** [comment]
After update Postgres and GEO dependencies it breaks system because they changed the syntax of using Postgres and also a lot of deprecated warnings.

Will be starting work again soon.

**Comment by azharmalik3** [comment]
Made changes in Postgres configuration according to a new version of Postgres https://github.com/evercam/evercam-server/commit/8bfc06e428a22ba3ea11656ffa2bd9c7a7434ce8#diff-6e705260e1d9c91538843dc5e61df7c2R35 and also changed the use of changeset in all data models https://github.com/evercam/evercam-server/commit/8bfc06e428a22ba3ea11656ffa2bd9c7a7434ce8#diff-b238bd8deeaadce0f1ad42dc1cf53a45R89.

Deployed media server (Erlang-19.3, Elixir-1.4.1) on the live server. It works but after 5 to 10 mins HTTPoison start giving timeout errors. Investigation timeout error locally with a large number of cameras and found that hackney-1.8.0 causes this erros. I forked HTTPoison repo and tried hackney version 1.8.4 but got same errors. Then tried 1.7.1 hackney (which is used in previous version of HTTPoison) version and it works stable.

It means hackney 1.8.0 and above version not stable for evercam. It works for few requests but not worked for large number of request (Like in evercam 300+ requests in one second).
