### ISSUE TITLE
Recording error due to device busy response

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#640]
Marco thoughts:

a) Make a change to the process that will slow down the pace of requests when we get a high proportion of Device Busy errors.

b) Consider how we could bring human attention to the issue, allowing a person ( you? Faisal? ) to be alerted to the fact that we have a problem camera so that they could intervene. e.g. by doing a manual restart of the NVR.

**Comment by azharmalik3** [comment]
If camera gives device busy errors more than images and reduce the images then:

First, we send a notification to camera owner and cc (to Azhar, Faisal) about the problem with the camera and ask for a manual reboot of the NVR to solve this problem.

After 1-hour if the problem remains then calculate average of images in 1-hour and slow down camera requests to that calculated average.

**Comment by marcoherbst** [comment]
Related: https://github.com/evercam/evercam-server/issues/487

**Comment by marcoherbst** [comment]
2 new Sumo Tasks:

1. Report to show Camera-ID v #Device-Busy's (in a given time period, e.g. 24hrs).
2. Alert if more than 500 DeviceBusy's per hour.

@azharmalik3

**Comment by marcoherbst** [comment]
Check this Issue also : https://github.com/evercam/evercam-server/issues/655

**Comment by marcoherbst** [comment]
Might you find info by understanding Hackney better?
https://github.com/benoitc/hackney#reuse-a-connection

Could this be relevant:
https://www.safaribooksonline.com/library/view/http-the-definitive/1565925092/ch04s07.html ?

**Comment by azharmalik3** [comment]
Closing this because we have created a sumo report for these errors and alert.
