### ISSUE TITLE
Physically separate our infinite storage cams from others?

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#647]

**Comment by ijunaid8088** [comment]
https://groups.google.com/forum/#!topic/seaweedfs/1YOXS5IWYcE

**Comment by ijunaid8088** [comment]
For follow up:

I have composed the question and also tested few things locally. Not a specific answer to that, But Discussion is going on in google group on this.

**Comment by marcoherbst** [comment]
2 other thoughts that would impact on this issue:
1. If we find the G-Drive backup to be very effective, then that would be a huge relief.
2. We also considered doing a continous extraction of low frequency images (e.g. 1 / 10mins) to a secondary backup. This, too, would relieve the pressue.

**Comment by marcoherbst** [comment]
Closing this, it's not longer on the roadmap.
