### ISSUE TITLE
Move authorization layer from evercam-api

### ISSUE THREAD

**Issue by mosic** [evercam/evercam-server#65]
The most important part of this task is checking the authorization of a user or a client who made the request. That's currently done in the `evercam-api` using `requester_rights_for` method.

This will be a major step in moving the features from `evercam-api` to `evercam-media`. After this we can first stop redirection and use media.evercam.io endpoints directly; move OAuth to `evercam-media`; then move the rest of the endpoints to it as needed.

We should add more information about the intended features for the authorization layer here. A good place to start getting familiar with the current implementation is the above mentioned method:  [`requester_rights_for`](https://github.com/evercam/evercam-api/blob/3c4af99e826bce9bf15246756e1b0e16981cd0cb/app/api/v1/helpers/authorization_helper.rb#L31).

**Comment by jgarciasacristan** [comment]
If no one else is looking at this, it sounds like an interesting project to play with and learn more phoenix/elixir stuff. :)

**Comment by marcoherbst** [comment]
Brave man @jgarciasacristan ! .... Right now this is being looked at by @fteem , and at first glance it looks like a monster ! We'll know more in a week or so.

**Comment by jgarciasacristan** [comment]
Cool. I'll follow this issue and eventually contribute to it.  One thing I
am going look next  is a way to move all SOAP stuff into a phoenix plug.
After my talk at Functional Cats a guy from
http://www.cultivatehq.com/ suggested
right that. An example of this approach for basic authentication is
available at https://github.com/CultivateHQ/basic_auth. This approach may
also help the OAuth move.

**Comment by marcoherbst** [comment]
@ijunaidfarooq  , is this still an open task ?

**Comment by marcoherbst** [comment]
Done.
