### ISSUE TITLE
More CR options please

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#653]
can we have a 1 per 5 mins AND 1 per 10 mins option please

**Comment by ijunaid8088** [comment]
It's a dashboard task, not server's. As its only an integer value which is going to be passed to endpoint.

**Comment by ijunaid8088** [comment]
Sorry for rushing into it. It's both side task. 

https://github.com/evercam/evercam-server/blob/master/web/models/cloud_recording.ex#L64

The current situation will only work for available options at the moment, not for the newly comings.

**Comment by ijunaid8088** [comment]
Its done.
