### ISSUE TITLE
Camera worker changes to reduce device_busy errors.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#655]
Phase 1:

- [ ] Remove retry option to get snapshot for `device_busy` errors or retry only once instead of 3 times.

Phase 2:

- [ ] Use synchronous calls to send snapshot request same as our Camba.tv. Wait for the response (before sending next request) and then send the next one after we get success/failure.

**Comment by marcoherbst** [comment]
Could this be relevant:
https://www.safaribooksonline.com/library/view/http-the-definitive/1565925092/ch04s07.html ?

**Comment by marcoherbst** [comment]
Might you find info by understanding Hackney better? 
https://github.com/benoitc/hackney#reuse-a-connection

**Comment by marcoherbst** [comment]
![appdevpoint-uptime-robot-dashboard](https://user-images.githubusercontent.com/5648894/40050990-11d97aa4-5831-11e8-95f6-9dd8eea4d50b.png)

**Comment by marcoherbst** [comment]
Covered in https://github.com/evercam/evercam-server/issues/853
