### ISSUE TITLE
/timelapses/  HD, low frequency recording to S3.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#660]
- [x] New tab on the dashboard "Timelapse"
- [x] Like CR, it will have settings, enabled, frequency, schedule etc.
- [x] Like CR, we will be able to browse the images. Let's try it without the calendar - just load all jpegs.
- [x] We may or may not show the images as a video (like we did in the timelapse application). (start with just jpeg navigation, not video).
- [x] My suggestion is that images are stored in S3 as I think we can then sleep better.
- [x] Default: 1 per 2 minutes 8am to 6pm using VH snapshot URL on Stream 1.
- [x] Since we made other parts of Evercam with symmetry in API and Dash URLs, please continue this and include here what the API calls will be.
- [x] (Maybe) One Folder Per Day (usually less than 600 images)

Endpoints for timelapse recordings and snapshots:

/cameras/:id/apps/timelapse-recording
/cameras/:id/timelapses/recordings/snapshots/:timestamp
/cameras/:id/timelapses/recordings/snapshots/:year/:month/days

**Comment by marcoherbst** [comment]
3 aspects:
1) Store the info properly in the camera object
2) Take in the Primary stream and offer a substream
3) Take in the substream & re-stream.

This needs discussion before tackling it.

**Comment by marcoherbst** [comment]
This will be a new tab on the dashboard "timelapse".  Like CR, it will have settings, enabled, frequency, schedule etc.
Like CR, we will be able to browse the images.
We may or may not show the images as a video (like we did in the timelapse application).
My suggestion is that images are stored in S3 as I think we can then sleep better.
Default: 1 per 2 minutes 8am to 6pm using VH snapshot URL on Stream 1.

**Comment by azharmalik3** [comment]
Endpoints for timelapse recordings and snapshots:

/cameras/:id/apps/timelapse-recording
/cameras/:id/timelapses/recordings/snapshots/:timestamp
/cameras/:id/timelapses/recordings/snapshots/:year/:month/days
