### ISSUE TITLE
Seaweed Save Error (Closed not Timeout)

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#665]
In past, we were having seaweed save timeout errors very frequently due to which calendar queries got slow and there were so many application errors on dashboard side. 

Today while looking to evercam server logs. When a seaweed error came, I noticed it wasn't about the timeout, It was about `close`..

According to sumo, they are coming from 02/03/2017. This could be the reason of Application errors which users are facing at the moment.

Seaweed Close error: This kind of error comes across when the Master server sends a request to volume server but volume server is down due to: there could be many reasons, one of those is No internet connection on that side.

**Comment by ijunaid8088** [comment]
https://github.com/chrislusf/seaweedfs/issues/467

**Comment by ijunaid8088** [comment]
As I have already mentioned many times, idleTimeout could be the solution to our many problems in seaweedFS. 

Chris also suggested that according to our current Hetzner Servers. https://github.com/chrislusf/seaweedfs/issues/467#issuecomment-285921341

**Comment by ijunaid8088** [comment]
https://github.com/chrislusf/seaweedfs/issues/467#issuecomment-286344363

**Comment by ijunaid8088** [comment]
https://github.com/chrislusf/seaweedfs/issues/467#issuecomment-286662160

**Comment by ijunaid8088** [comment]
Follow up for other:

After reducing the max connections and timeout, errors have been reduced. as from Sumo Logic report.

14/03/2017 Errors were: **12,263**..
Fix Deployed on 15th of March.
15/03/2017 Errors were: **4481**.
16/03/2017 Errors were: **3,579**..

They are reducing hopefully in coming days.. they will reduce more, then I will close this issue.

**Comment by marcoherbst** [comment]
Great news. Well done.

**Comment by ijunaid8989** [comment]
This fix only worked for few days, After 2 or 3 days, The count of errors started varying again. And right now they are again many in numbers but not with a sequence, someday they are 5K and someday they are 10K.

**Comment by ijunaid8989** [comment]
After having no clue about this I posted on Hackney Github repository to get some opinions

https://github.com/benoitc/hackney/issues/398

**Comment by ijunaid8989** [comment]
For follow up:
Updating the HTTPoison works for this issue. The reason for updating it, was only to get updated with hackney, as we are using the hackney pool for making requests. Now we are in version 0.11.1(1.7.X hackney).

Before Deploy:
![image](https://cloud.githubusercontent.com/assets/13561999/24468632/4f6532ee-14d2-11e7-8065-7c856d3537e1.png)

After Deploy
![image](https://cloud.githubusercontent.com/assets/13561999/24468811/e62b8fca-14d2-11e7-945e-760ea34521dc.png)

The error count decreased to a very minimum number, Today there is just 7 seaweed closed errors till now. I have looked for a way to close all those HTTP connection which are unused or remained opened with no reason in seaweedFS master server, But couldn't find anything about it.

**Comment by ijunaid8989** [comment]
https://github.com/benoitc/hackney/issues/398#issuecomment-290620487

**Comment by ijunaid8989** [comment]
It's almost done and going well. 

If something alarming will come again, I will create the other issue for it. For now it's OK.
