### ISSUE TITLE
Migrate from UserDefinedCameraID to IntegerCameraID on Seaweed

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#667]
This is a placeholder for the task. I amn't yet confident about this.

Currently it seems to me to be the right thing to do as it is the only significant change required to enable changing of UserDefinedIDs.

I wonder if Seaweed/Media could be configured temporarily to respond to either variant during a renaming period. @ijunaid8989 might have a better idea.

**Comment by ijunaid8989** [comment]
My confidence level for this task is only 2%. I have managed to make this change locally, But there is not only one thing which is related to camera_exid many other things are also affecting and its huge change with some non-undo results.

**Comment by marcoherbst** [comment]
I'm going to close this until a time when we really need it.
