### ISSUE TITLE
Move SnashotExtractor and EvercamAdmin to HetznerVM

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#674]
https://www.hetzner.de/ie/hosting/produkte_vserver/cx40

https://github.com/evercam/evercam-admin/issues/284

**Comment by marcoherbst** [comment]
Lovely.

When you do this, please consider strongly how to get the same level of info about usage & error reporting as we currently get from Heroku. It would be a pity to loose that.

**Comment by ijunaid8989** [comment]
https://www.digitalocean.com/community/tutorials/deploying-a-rails-app-on-ubuntu-14-04-with-capistrano-nginx-and-puma
https://www.digitalocean.com/community/tutorials/how-to-deploy-a-rails-app-with-git-hooks-on-ubuntu-14-04
https://www.phusionpassenger.com/library/walkthroughs/deploy/ruby/ownserver/standalone/oss/deploy_app_main.html
https://gist.github.com/julionc/4006d5b2091496600fc2

**Comment by ijunaid8989** [comment]
As a reference to run 2 app on one Nginx http://stackoverflow.com/questions/22064397/how-to-run-two-apps-on-ec2-with-nginx

**Comment by ijunaid8989** [comment]
It's done. 
Snapshot Extractor is running on Hetnzer.
Evercam Admin has 3 issues and I will solve them later, I will create that issue in evercam admin. Other than that everything is working fine.
