### ISSUE TITLE
User Segregation (At Admin level)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#677]
New field in User Table called "Custom Tag" which is a text field.
(this is similar to how we made Payment Method)
To start with, custom Tags are:  Construction, Smart City, Cloud CCTV, Other
Plan is: All users who register on a special page, or who comply with special conditions (e.g. have been shared a construction camera) are to be tagged "Construction"
and then we will show them a slightly different dashboard.
when making this, you can make anyone who has a construction camera share into tag = Construction.

NB. Before beginning work on this, ask me 1 more time to confirm. :| .....

**Comment by marcoherbst** [comment]
@azharmalik3  ....

VQ has several ideas related to customising the dashboard for construction customers.  I've been holding off on them as I didn't want to make things more complex. What about:

Let's use the "Payment Method" field with a new type: Construction. 

For these users (we will auto-assign all who share a camera that is in the construction account) they would not see the billing tab from the left hand navigation. 

There may be other dashboard customisations later, also specific for construction clients. e.g. some marketing collateral and/or features such as Evercam Compare. ....

... When you've had a chance to think about this, let's have a voice call as I'm concerned about any performance issues or technical debt introduced, this feels a bit hacky.

**Comment by marcoherbst** [comment]
- [ ]  Add new payment type: Construction
- [ ] Move column "Payment Type" on Admin Users report to left side. (Column 1).
- [ ] Do async with Intercom for all Intercom Construction = Evercam Construction (ONCE)

**Comment by azharmalik3** [comment]
@marcoherbst All checkpoints completed.

**Comment by marcoherbst** [comment]
Lovely. Will add a Multi-select & Modify Issue to Admin.
https://github.com/evercam/evercam-admin/issues/310
