### ISSUE TITLE
Process crash while logging camera online offline log

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#683]
Few times this process fails to log camera status
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/db_handler.ex#L86
due to which other events are not being sent as well.

As mentioned here https://github.com/evercam/evercam-dashboard/issues/1513

**Comment by marcoherbst** [comment]
@ijunaid8989  I'm closing this too as you are dealing with it elsewhere it seems to me.
