### ISSUE TITLE
Backup all Seaweed data & index files to G-Drive

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#687]
including these steps:
1. backup one DAT
2. try and restore it elsewhere (without idx rebuild it). Does it work?
3. backup the whole lot.

**Comment by ijunaid8989** [comment]
https://github.com/prasmussen/gdrive

**Comment by ijunaid8989** [comment]
As follow up: the upload is going on here https://drive.google.com/drive/u/0/folders/0B8RgYtlwEE1sdG8tYTZsQ291ZkE

and we have uploaded 13.4T till now.

**Comment by marcoherbst** [comment]
Update: (Junaid you can edit this)
The G-Drive sync works but is pretty slow (about 2TB / day)
The Filer Folder sync worked nicely (but is useless without the data file sync).
So, we're pausing both of these syncs and considering it closed a closed issue.
