### ISSUE TITLE
Unable to pull evercam-model

### ISSUE THREAD

**Issue by alex-fernandez** [evercam/evercam-server#693]
Was there a way to pull evercam-model?

**Comment by ijunaid8989** [comment]
They have been shifted to evercam-dash.
https://github.com/evercam/evercam-dashboard/tree/master/app/models/evercam_models.

Anyhow they have no concern with evercam-server. 

Are you trying to setup evercam-server locally?

**Comment by alex-fernandez** [comment]
Hi @ijunaid8989, was there a way to build the whole stack from local, I'm have followed the following instruction https://github.com/evercam/evercam-devops.

**Comment by ijunaid8989** [comment]
On which OS you are at the moment? 
Have you installed the same Ansible version?

**Comment by alex-fernandez** [comment]
not yet, Im using  mac

**Comment by alex-fernandez** [comment]
Base on this 
https://github.com/evercam/evercam-devops
evercam-models @ b0d5f07

evercam-models is needed in checkout git submodule foreach --recursive "git checkout master && git pull

**Comment by ijunaid8989** [comment]
1. Virtualbox
2. Vagrant
3. Python
4. Ansible 2.0.1.0
5. Git
These are prerequisites. You should have installed those things. 
Also am not sure about mac. But for all those things locally working , You need to be on ubuntu and mostly on 14.04.

On another hand, You can setup everything on your mac as well but not with devops.

**Comment by ijunaid8989** [comment]
You can skip that step. Evercam Models aren't necessary at all in evercam-server.
When you say locally, Are you going to run devops on Vbox or you want it on your local machine? out of Vbox?

**Comment by alex-fernandez** [comment]
I want to run locally then later on, I want to dockerize it. Just a side note, do you have a docker instance for these apps?

**Comment by ijunaid8989** [comment]
I am afraid, we don't.

**Comment by alex-fernandez** [comment]
Alright, what can you suggest me in starting to build the app. Ill just pull each app manually and omiting evercam_models?

**Comment by ijunaid8989** [comment]
Yeah, You can omit evecam models. You don't need them, in any case they are present in evercam dashboard models.
