### ISSUE TITLE
Decide / Explain the interval between requesting a new image / using a stored one.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#704]
re: Shared camera purple broken image. Search "Purple-duplicate" in email.

**Comment by marcoherbst** [comment]
From talking to @azharmalik3 he thinks there is no such scenario where "if we have an image that is <x ms old , then use it instead of getting a new one".

If that is true, then maybe we should add that scenario, where x = , say , 300ms ??

**Comment by azharmalik3** [comment]
Added functionality to get the image from saved images if we have image 500ms old otherwise get new image from the camera.
