### ISSUE TITLE
Frames repeating after getting some new frames

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#706]
Checkout following camera dorset-street-i/recordings/snapshots/2017-04-24T07:43:15.000Z. This camera repeat frame after 1 or two frames.

frame 1144 = 08.46.06
 
frame 1145 = 08.45.54 
frame 1146 = 08.46.06 (repeat) 
frame 1151 = 08.46.06 (repeat)

**Comment by marcoherbst** [comment]
@ijunaid8989  related to  https://github.com/evercam/evercam-server/issues/744

**Comment by marcoherbst** [comment]
Duplicate
