### ISSUE TITLE
Consider how to optimise availability of most recent thumbnail.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#708]
The graph below shows the change from not storing locally, but rather sending to Seaweed.

NB increased Network I/O.  (After 6:40am)

Presumeably, storing a copy in RAM or SD card would also be a benefit. 

This is for a future optimisation.

![image](https://cloud.githubusercontent.com/assets/5648894/25379178/19e44f74-29a4-11e7-91d0-af6683db283f.png)

**Comment by azharmalik3** [comment]
Functionality already added to save thumbnail in RAM and get thumbnail from RAM instead of seaweed.

After this changing network I/O decreased.
