### ISSUE TITLE
HTML widget to allow browsing of locally stored video.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#71]
An IP camera with SD Card storage or an NVR/DVR often has a web interface for navigating stored video. In Hikvision's case, this is an ActiveX component that needs to be installed.

I wonder, with the use of OnVif protocol for stored video, is this information about locally stored files available ... and could we build a web interface to access it.

Then, how nice can this interface be?

Camba.tv implemented this for Y-Cams to be just a list of files which was quite acceptable for many use cases. We implemented it for Hikvision by proxying the activeX, which worked extremely well (we've implemented the same idea in Evercam) ... but the whole plugin thing is too painful, especially with Chrome's recent blocking of them.

Just wondering if this might be a wonderful opportunity for a further implementation of OnVIF ... it will also require some smart thinking on the frontend.

@jgarciasacristan does this make sense to you? what do you think? I can look around for a device that has onvif profile-S (I think that's what it's called).They may still be rare.

**Comment by jgarciasacristan** [comment]
It is actually profile-G
http://www.onvif.org/Default.aspx?Contenttype=ArticleDet&tabID=110&moduleId=487&Aid=59&PR=PR
http://www.onvif.org/Portals/0/documents/specs/ONVIF_Profile_G_Specification_v1-0.pdf

It sounds doable to me.
I just need a camera to start playing with recordings. :-)

**Comment by marcoherbst** [comment]
Great, there's a camera on its way to your account as we speak.

From here: http://www.onvif.org/FindaProduct/ProfileProducts.aspx we can
see a list of products that are Profile G compatible. :)

cc @vinniequinn @mosic

When it comes to doing the front end, we'll see if we can pull in
@azharmalik3 or someone else.

M

On 1 October 2015 at 22:53, jgarciasacristan <notifications@github.com>
wrote:

> It is actually profile-G
>
> http://www.onvif.org/Default.aspx?Contenttype=ArticleDet&tabID=110&moduleId=487&Aid=59&PR=PR
>
> http://www.onvif.org/Portals/0/documents/specs/ONVIF_Profile_G_Specification_v1-0.pdf
>
> It sounds doable to me.
> I just need a camera to start playing with recordings. :-)
>
>
> On Thu, Oct 1, 2015 at 9:23 PM, Marco Herbst <notifications@github.com>
> wrote:
>
> > An IP camera with SD Card storage or an NVR/DVR often has a web interface
> > for navigating stored video. In Hikvision's case, this is an ActiveX
> > component that needs to be installed.
> >
> > I wonder, with the use of OnVif protocol for stored video, is this
> > information about locally stored files available ... and could we build a
> > web interface to access it.
> >
> > Then, how nice can this interface be?
> >
> > Camba.tv implemented this for Y-Cams to be just a list of files which was
> > quite acceptable for many use cases. We implemented it for Hikvision by
> > proxying the activeX, which worked extremely well (we've implemented the
> > same idea in Evercam) ... but the whole plugin thing is too painful,
> > especially with Chrome's recent blocking of them.
> >
> > Just wondering if this might be a wonderful opportunity for a further
> > implementation of OnVIF ... it will also require some smart thinking on
> the
> > frontend.
> >
> > @jgarciasacristan <https://github.com/jgarciasacristan> does this make
> > sense to you? what do you think? I can look around for a device that has
> > onvif profile-S (I think that's what it's called).They may still be rare.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/evercam/evercam-media/issues/71>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evercam/evercam-media/issues/71#issuecomment-144860637>
> .
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by jgarciasacristan** [comment]
No new camera on my account so far. Have you added a new camera today?

**Comment by jgarciasacristan** [comment]
Great news! To my surprise "Central Bank New Building" camera now reacts to OnVif commands. Below is the raw answer from invoking GetRecordingJobs. As expected, there are no jobs available but the response is successful. So, I can assume that www.onvif.org/onvif/ver10/Recording.wsdl operations are supported. Glad to be back in action. :-)
`%HTTPotion.Response{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\r\n<env:Envelope xmlns:env=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:soapenc=\"http://www.w3.org/2003/05/soap-encoding\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns:xs=\"http://www.w3.org/2001/XMLSchema\" xmlns:tt=\"http://www.onvif.org/ver10/schema\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:timg=\"http://www.onvif.org/ver20/imaging/wsdl\" xmlns:tev=\"http://www.onvif.org/ver10/events/wsdl\" xmlns:tptz=\"http://www.onvif.org/ver20/ptz/wsdl\" xmlns:tan=\"http://www.onvif.org/ver20/analytics/wsdl\" xmlns:tst=\"http://www.onvif.org/ver10/storage/wsdl\" xmlns:ter=\"http://www.onvif.org/ver10/error\" xmlns:dn=\"http://www.onvif.org/ver10/network/wsdl\" xmlns:tns1=\"http://www.onvif.org/ver10/topics\" xmlns:tmd=\"http://www.onvif.org/ver10/deviceIO/wsdl\" xmlns:wsdl=\"http://schemas.xmlsoap.org/wsdl\" xmlns:wsoap12=\"http://schemas.xmlsoap.org/wsdl/soap12\" xmlns:http=\"http://schemas.xmlsoap.org/wsdl/http\" xmlns:d=\"http://schemas.xmlsoap.org/ws/2005/04/discovery\" xmlns:wsadis=\"http://schemas.xmlsoap.org/ws/2004/08/addressing\" xmlns:wsnt=\"http://docs.oasis-open.org/wsn/b-2\" xmlns:wsa=\"http://www.w3.org/2005/08/addressing\" xmlns:wstop=\"http://docs.oasis-open.org/wsn/t-1\" xmlns:wsrf-bf=\"http://docs.oasis-open.org/wsrf/bf-2\" xmlns:wsntw=\"http://docs.oasis-open.org/wsn/bw-2\" xmlns:wsrf-rw=\"http://docs.oasis-open.org/wsrf/rw-2\" xmlns:wsaw=\"http://www.w3.org/2006/05/addressing/wsdl\" xmlns:wsrf-r=\"http://docs.oasis-open.org/wsrf/r-2\" xmlns:trc=\"http://www.onvif.org/ver10/recording/wsdl\" xmlns:tse=\"http://www.onvif.org/ver10/search/wsdl\" xmlns:trp=\"http://www.onvif.org/ver10/replay/wsdl\" xmlns:tnshik=\"http://www.hikvision.com/2011/event/topics\" xmlns:hikwsd=\"http://www.onvifext.com/onvif/ext/ver10/wsdl\" xmlns:hikxsd=\"http://www.onvifext.com/onvif/ext/ver10/schema\"><env:Body><trc:GetRecordingJobsResponse></trc:GetRecordingJobsResponse>\r\n</env:Body>\r\n</env:Envelope>\r\n", headers: [Connection: "close", "Content-Length": "1980", "Content-Type": "application/soap+xml; charset=utf-8", Date: "Thu, 05 Nov 2015 23:48:19 GMT", Server: "App-webs/"], status_code: 200}
:ok`

**Comment by marcoherbst** [comment]
... this could be VERY exciting, if possible, via OnVIF. It also is related (possibly) to Snapshot Extractor Local Storage Edition

**Comment by marcoherbst** [comment]
@ijunaid8088 . This is a rather large and daunting task.

If, during the initial investigation you thought that it would be easier to do a quick and dirty version of the snapshot extractor, then I would consider that to be a very worthwhile stepping stone. 

Very worthwhile indeed.

**Comment by ijunaid8088** [comment]
@marcoherbst Sure will consider your suggestion. :)

**Comment by marcoherbst** [comment]
@ijunaid8088  , Here are some guesses:

1. The HIk doc will not be the full story. You will also want to be familiar with the OnVIF spec. I *think* spec G is the one that deals with local storage: http://www.onvif.org/Portals/0/documents/specs/ONVIF_Profile_G_Specification_v1-0.pdf

2. While you may initially be looking for the sort of XML responses that will allow you to recreate /recordings or /snapshot-extractor , I doubt you will find them, so, instead, start out with the intention of retrieving and visualising *any* info you can get about local recordings.

**Comment by marcoherbst** [comment]
@ijunaid8088 leave your comments on where you got to on this. Then move to long finger.

**Comment by marcoherbst** [comment]
@ijunaid8088 , once your thoughts on this are clear, please put them in a concise manner, in this issue. From what I've heard so far, I think it makes sense to first talk it through with Azhar or Nain.

**Comment by marcoherbst** [comment]
I think, given the progress by @azharmalik3  on doing this for Hikvision, we can close this issue. 

It still is interesting to have an OnVIF generalised solution... but it's far out.
