### ISSUE TITLE
Snapshot controllers are ignoring withdata=true/false

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#711]

**Comment by ijunaid8989** [comment]
Discussed with Sir @azharmalik3 

We don't need this parameter now in any case, whether it's being ignored or not, In past we were using the database for snapshots, where it was being used, just to make it more flexible for getting the only timestamp of snapshot, and the other way around (full information alongside with image)..

as Now we are using SeaweedFS, so We are getting all information from there, (creation date as well), there is no need of this param, in any case, we are going to query the same, whether is `with_data=true` or not.

So we are not using with_data=true or not true anywhere (It's being mentioned in HTTP request from the dashboard), But it was when we were on the old stack.

**Comment by ijunaid8989** [comment]
its done. 

we settled with removing `with_data=true` from everywhere.
