### ISSUE TITLE
Intentionally Offline Camera Status (Project Finished)

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#714]
With ability to choose a suitable image.

No Live View
No Snapmails
Suitable Messages

Status: Finished

Azhar make a Google Doc with a spec of everything you can think of .... ??

**Comment by marcoherbst** [comment]
https://github.com/evercam/evercam-dashboard/issues/1757 Same as this.

**Comment by azharmalik3** [comment]
#### Camera Model Changes
Currently using is_online (boolean) field to ensure camera online (true) or offline (false)
https://github.com/evercam/evercam_models/blob/master/lib/evercam_models/camera.ex

Change field name to status (enumerated type).
0 => online
1 => offline
2 => project finished 


#### Server Changes
Update camera status online/offline
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/db_handler.ex#L59
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/db_handler.ex#L148

#### Camera worker 
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/worker.ex#L222

#### Camera deletion
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/deletion.ex#L76

#### Update camera thumbnail
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/snapshot/update_thumbnail.ex#L76

#### Evercam Bot
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media/evercam_bot/commands.ex#L144

#### Camera Controller
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media_web/controllers/camera_controller.ex#L588

#### Camera Share Controller
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media_web/controllers/camera_share_controller.ex#L274

#### Snapshot Controller
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media_web/controllers/snapshot_controller.ex#L604

#### Camera View
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media_web/views/camera_view.ex#L50

#### Public View
https://github.com/evercam/evercam-server/blob/master/lib/evercam_media_web/views/public_view.ex#L21

#### Add Camera Log
https://github.com/evercam/evercam-server/blob/master/lib/mix/tasks/add_camera_logs.ex#L15

@ijunaid8989 Discuss with @azharmalik3 before start.

**Comment by marcoherbst** [comment]
@ijunaid8989  status?

**Comment by ijunaid8989** [comment]
Everything is done from server as well as from dashboard and admin.

BUT

I didnt add the undo functionality, of course, you can make it online back again from finished but snapshot worker and snapmail workers will not get started straight away.

I am going to add this thing and then i i will close the issue.

**Comment by ijunaid8989** [comment]
its done
