### ISSUE TITLE
Create new endpoints for username and email address validation.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#735]

**Comment by marcoherbst** [comment]
@affan00  ... validation only? what does this mean? write this issue better please.

**Comment by affan00** [comment]
Need a new endpoint for spotting username and email address either they exist in DB or not.

Currently, on clicking signup button user come to know that email and username are already registered, I want to validate this on run time before pressing the submit button.

**Comment by ijunaid8989** [comment]
@affan

You can use the new endpoint now..

its `/v1/users/exist/:input` POST, input could be email or username and the resulting values will be

- If user exists with this username or email it will return `%{user: true}`
- If user doesn't exist with this username or email it will return `%{user: false}`
