### ISSUE TITLE
Work out why Hackney 1.8+ does not work with Evercam

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#737]
HTTPoision-0.11.2 starts giving timeout errors after 5 to 10 minutes. Investigate timeout error locally with a large number of cameras and found that hackney-1.8.0 causes this error. I forked HTTPoison repo and tried Hackney version 1.8.4 but got same errors. Then tried 1.7.1 Hackney (which is used in the previous version of HTTPoison-0.11.1) version and then it works stable.

It means Hackney 1.8.0 and above version not stable for evercam. It works for few requests but not work for a large number of request (Like in evercam 300+ requests in one second).

**Comment by marcoherbst** [comment]
@ijunaid8989 you'll see I changed the title of this issue.

If you think you can, with the added wisdom of time, shorten & improve the issue you posted on Hackney https://github.com/benoitc/hackney/issues/398 then, great ... if not, that's ok.

I'll push this task into October anyway.

**Comment by Hajto** [comment]
From Changelog of version 1.8.0 of hackney:
```
fix: use connect timeout when retrieving from the pool (#402)
```

Please check this PR of hackney:
https://github.com/benoitc/hackney/pull/402

It might be closely related to problem you are experiencing.

**Comment by Hajto** [comment]
So my hypothesis is that you are experiencing timeouts because Cameras can be slow ah and you are running out of connection pool on hackney. The fix is proper queueing mechanism or tinker with pool to accept more requests and a time (https://github.com/benoitc/hackney#use-the-default-pool).

**Comment by benoitc** [comment]
this should have been fixed with the latest master.  Let me know

**Comment by ijunaid8989** [comment]
its done and deployed, thanks @benoitc :)
