### ISSUE TITLE
Logs are missings (Don't update on time)

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#742]
For further clarification see these cameras:
carrolls zoo cam
cian park 1
cian park 2

Example:
Last offline snapshot time:
![went-offline-live](https://user-images.githubusercontent.com/14149453/27379757-fcb7b034-5695-11e7-98d1-7891e150384a.png)

Went offline logs time:
![went-offline](https://user-images.githubusercontent.com/14149453/27379788-1c9ec32e-5696-11e7-8157-a4ad031a6d22.png)

**Comment by ijunaid8989** [comment]
closing this in reference of https://github.com/evercam/evercam-server/issues/727
