### ISSUE TITLE
Jpeg recordings out of sequence

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#744]
https://dash.evercam.io/v1/cameras/testv-cxnfz/archives#
at 23.41:00 Jumps to 23.41:17 then 23.41.15 then 23.41:16

**Comment by marcoherbst** [comment]
@ijunaid8989 ... could it be one for you?

**Comment by ijunaid8989** [comment]
Okay I am taking it, It would worth a try, at least...

**Comment by marcoherbst** [comment]
Covered in https://github.com/evercam/evercam-server/issues/853
