### ISSUE TITLE
Need 'latest snapshot timestamp' in latest snapshot endpoint.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#749]
I want to update the calendar on Recording when clicking on 'Last', Right now there is no created_at date available in the latest snapshot endpoint.

**Comment by marcoherbst** [comment]
Are you sure?

My guess is that not all cameras have a snapshot on created date.

I'm surprised you want this date. The oldest snapshot is not necessarily the same as the create date.

**Comment by affan00** [comment]
Marco, I need 'latest snapshot timestamp' in order to update the calendar when clicking on 'Last >>' on Recording tab.

**Comment by marcoherbst** [comment]
Ah, right, I thought when you said "created-at" you meant camera creation date. 

But if you have snapshot ID, the ID is the creation date, no? (unix timestamp)

**Comment by ijunaid8989** [comment]
Latest endpoint: https://media.evercam.io/v1/cameras/costamesa/recordings/snapshots/latest?

and results are like that

```
{
status: "ok",
data: "data:image/jpeg;base64,/9j/4A....so on
}
```
Oldest endpoint: https://media.evercam.io/v1/cameras/costamesa/recordings/snapshots/oldest?

and results are like that
```
{
status: "ok",
data: "data:image/jpeg;base64,/9j/4A....so on
created_at: 1476421111
}
```

**Comment by azharmalik3** [comment]
@affan00 snapshot timestamp added into the response and now you can use in the dashboard to highlight calendar.
