### ISSUE TITLE
Offline cameras still make requests and feature an awful lot in the log files.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#753]
Many cameras are offline but they are still sending image requests and creating so many errors. 

For more information see
Sumo Report: https://service.eu.sumologic.com/ui/#section/search/ywgvD3mYiUpNvk4JkK1dLAof9aJA6KMcrthKwss6

**Comment by marcoherbst** [comment]
NB.

It is correct that an offline, recording camera, would continue to retry. When tackling this task, be sure to first understand what the behaviour should be and understand the difference between a permanently offline camera and a temporarily offline camera.

**Comment by ijunaid8989** [comment]
This issue is not replicable, so closing this..

Just for information: I looked into the old data and there were 2 cameras with recording on from vpn.evercam.io , `dannycam-3` and `Dannycam4`, they both were on CR recording and also infinity, but they were offline. Those cameras were the reason of those logs, in any else case, the above scenario is not happening.
