### ISSUE TITLE
Implement basic stats for all cameras

### ISSUE THREAD

**Issue by shankardevy** [evercam/evercam-server#76]
The idea is to leverage the GenServer process foreach worker and have these stats by passing on relevant messages to the server process.
1. Number snapshots taken in the last x days, hours, minutes
2. Snapshot taken per camera in the last x days, hours, minutes 
3. List of online and offline cameras.
4. List of errors generated by various cameras
5. Average time taken to fetch a snapshot
6. List of cameras that return timeouts
7. Downtime per camera.

@marcoherbst stressed the need for a stable system before adding more users. These stats should give us objective way of defining that stability.

**Comment by azharmalik3** [comment]
@mosic I want to take this issue?

**Comment by mosic** [comment]
@azharmalik3 I think that this would be too complex for the first task in evercam-media, a smaller/simpler one would be better.

Or, if you really want to work on this, split it into several smaller parts and then tackle the first one.

**Comment by marcoherbst** [comment]
https://hackernoon.com/a-tour-of-elixir-performance-monitoring-tools-aac2df726e8c#.rq0sp0663

**Comment by marcoherbst** [comment]
@azharmalik3  remember this?  A long time ago :) ...  and quite related to the work you've been doing.

**Comment by azharmalik3** [comment]
@ma Yes, It's related to this task.

**Comment by marcoherbst** [comment]
@azharmalik3 I think you've solved every important part of this, the rest is not needed. Closing. thanks.
