### ISSUE TITLE
Update Elixir version to latest.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#776]
Update Elixir version to latest 1.5.1 (current).

The major change is to remove the `GenEvent` and use alternatives, for follow up please see

https://hexdocs.pm/elixir/GenEvent.html#module-alternatives
https://github.com/evercam/evercam-server/issues/190
https://github.com/evercam/evercam-server/issues/763#issuecomment-320865779

**Comment by marcoherbst** [comment]
Duplicated, closing.
