### ISSUE TITLE
Work out CPU usage issues on h265

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#779]
Will require some testing to see what changes might be needed on our platform:
https://www.google.ie/search?q=ffmpeg+h265+to+hls&oq=ffmpeg+h265+to+hls&aqs=chrome..69i57j0l2.5192j0j7&sourceid=chrome&ie=UTF-8

**Comment by azharmalik3** [comment]
Used following link (https://trac.ffmpeg.org/wiki/Encode/H.265) to solve H265 issue.

I just used following arguments in command to solve this issue:

`-c:v libx264 -pix_fmt yuv420p`

**Comment by azharmalik3** [comment]
@marcoherbst 
Opening this issues because after using `-c:v libx264` params in live stream FFmpeg command it increased CPU usage which reached to 100% and slows down our media server.

Re-thinking about this to reduce CPU usage.

**Comment by marcoherbst** [comment]
I wonder if a GPU might help?
https://www.hetzner.com/dedicated-rootserver/ex51-ssd-gpu?country=ie

**Comment by marcoherbst** [comment]
Closing as this is covered in #928
