### ISSUE TITLE
Local Recordings needs to fail elegantly when no recordings are available.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#782]

**Comment by marcoherbst** [comment]
https://dash.evercam.io/v1/cameras/hikvis-u7j/local-recordings?from=2017-08-18T11:00:00.000Z&to=2017-08-18T11:59:59.000Z

@azharmalik3

**Comment by azharmalik3** [comment]
Used following link (https://trac.ffmpeg.org/wiki/Encode/H.265) to solve H265 issue.

I just used following arguments in command to solve this issue:

`-c:v libx264 -pix_fmt yuv420p`

**Comment by azharmalik3** [comment]
Added a generic message on failure to load stream because it's not possible to get FFmpeg response from spawn process.
