### ISSUE TITLE
Create A Wiki Page to Explain GET, POST, snapshot endpoints, how they work incl. directory structure & use of notes.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#788]
@ijunaid8989  this is for you, please.  Bottom of August Milestone.

**Comment by ijunaid8989** [comment]
https://github.com/evercam/evercam-server/wiki/Snapshot-POST-Endpoint.
https://github.com/evercam/evercam-server/wiki/Snapshot-GET-Enpoint.
https://github.com/evercam/evercam-server/wiki/Directory-Structure.


its done.
