### ISSUE TITLE
Port open/close endpoint doesn't seems to be reliable.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#789]
Sometimes the port check endpoint returns the wrong response. 
I tested it many times from the front-end point of view but it seems to be server side issue.

The camera is online but on details, port status is closed. 

For testing purposes please check this API endpoint https://media.evercam.io/v1/cameras/port-check?address=IP&port=8040

https://dash.evercam.io/v1/cameras/evercam-office-iii/details

Here is the snapshot example, sometimes it shows closed status.
![portisclosededit](https://user-images.githubusercontent.com/14149453/29361185-cb9286c4-829f-11e7-94b7-59d47eb97673.png)

Endpoint response in console
![portisclosedconsoleedit](https://user-images.githubusercontent.com/14149453/29361088-6813952a-829f-11e7-9b7e-c2842130a511.png)

Sometimes it shows open status.
![portisopenstatusedit](https://user-images.githubusercontent.com/14149453/29361140-9dec07ea-829f-11e7-80ec-601b561273b6.png)

https://github.com/evercam/evercam-dashboard/issues/1761

**Comment by marcoherbst** [comment]
I'm closing this. 

I don't think there's really an issue with the media endpoint itself. It seems reliable enough.

I do believe that the user experience fails more frequently than the endpoint itself ... @affan00 might try doing an auto-retry to see if he can improve that slightly.
