### ISSUE TITLE
Basic Auth doesn't work with Foscam

### ISSUE THREAD

**Issue by liutingdu** [evercam/evercam-server#79]
Camera model: Foscam FI9803P

The correct snapshot URL is:

```
http://ip:port/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=username&pwd=password
```

The snapshot URL we have in our database is correct, but it only takes parameters for authentication. Basic auth doesn't work. I tested this with a real camera. But I am not sure is it the same for all Foscam cameras.

We should handle this on server side.

@marcoherbst Let me know if this issue shouldn't belong to evercam-media then I can move it to somewhere else.

**Comment by marcoherbst** [comment]
Not on Roadmap
