### ISSUE TITLE
Snapshot Extractor for Local Storage

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#794]
Not sure who this is for or where it will be built ... probably @azharmalik3 with help from Junaid.

**Comment by marcoherbst** [comment]
@azharmalik3 This is kind of done, maybe you could just add some notes about any incomplete aspects or parts that you think need to be revisited and we'll move it into a future milestone.  I guess mostly it is about finding when it breaks , e.g.:

1. Dont allow user to do an extraction outside reasonable parameters (e.g. 1yr? ... or what is a reasonable max?)

2. Build an Admin interface so that Mark or a non-Azhar user can use this.

**Comment by azharmalik3** [comment]
Snapshot extraction completed and also, added admin report to send a request for snapshot extraction. https://admin.evercam.io/nvr/snapshot_extractor
