### ISSUE TITLE
Snapmail - History in DB.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#805]
This is a 2 part task:

- [x] 1. Store sending history in DB (for discussion, as I understand, jpegs get their own folder in Seaweed already).
- [x] 2. Admin reports of Snapmail configs & History

**Comment by ijunaid8989** [comment]
As a first step, and the first part of the Issue, I am going to save these fields in DB regarding a snapmail.

1. Recipients
2. Date and Time
3. Camera Name (Basically camera Id.)

also on other hands, If we don't want to save anything to DB and get the report at runtime while using mailgun api.

https://documentation.mailgun.com/en/latest/api-events.html#examples

@marcoherbst Suggestions are open, there is a room for discussion here.

**Comment by ijunaid8989** [comment]
For follow up:

- [ ] Make changes to mailgun client to get the Email template, as right now its returning `{:ok, 'OK'}`
- [ ] Save full email template to DB, alongside with datetime and camera_id
- [ ] Show it from admin report with DateTime search and on Click in pop up.

**Comment by ijunaid8989** [comment]
Its done.
