### ISSUE TITLE
Containerise application

### ISSUE THREAD

**Issue by Hajto** [evercam/evercam-server#815]
It will be a good idea to migrate to using Erlang releases than running `mix run` on the bare metal. Erlang releases are complete packages including ERTS (erlang runtime system) and project. It can be run on virtually anything.

When app would be put into a container (for example docker) it can be run on external machine and traffic can be redirected to it.

**Comment by marcoherbst** [comment]
@ijunaid8989 if you're thinking of hot releases, then you probably will also need to form an opinion on this idea. It may not be for us, but I'd like you to think about it.

**Comment by marcoherbst** [comment]
Closing as really this is covered in #485
