### ISSUE TITLE
Reconsider vendor model endpoint

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#822]
In the current system, we are requesting vendor/models twice to get vendor list and specific vendor for camera single page and we do this on each camera request which is causes to more CPU usage.

https://rpm.newrelic.com/accounts/1020772/applications/49226711/transactions?type=app#id=5b225765625472616e73616374696f6e2f5572692f536e617073686f74436f6e74726f6c6c6572236c697665222c22225d

We should do this in one request and stop repeated requests.

**Comment by marcoherbst** [comment]
@azharmalik3 this sounds like it would have a significant impact on performance. I'm putting it in the October milestone.

**Comment by marcoherbst** [comment]
@azharmalik3 status?

**Comment by azharmalik3** [comment]
@marcoherbst It's done.
