### ISSUE TITLE
Ability to delete jpegs esp. for timelapse

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#824]
Add a delete snapshot endpoint for deleting jpegs within a time range. with an Admin interface,

The user will add starting URL and end URL from cloud recordings. after giving the available range for an hour. Jpegs will be deleted.

**Comment by marcoherbst** [comment]
@ijunaid8989 ... is this done?

**Comment by ijunaid8989** [comment]
yes, its done and implemented for one hour range only.

https://github.com/evercam/evercam-admin/issues/409

**Comment by ijunaid8989** [comment]
Its done through evercam admin with an interface, also added an endpoint to sever to work between 2 dates ranges, Unix and rfc3339_utc (dash.evercam.io/..../recordings/snapshots/**2018-05-08T07:00:00.000Z**)
