### ISSUE TITLE
Create Animated GIF of Compare

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#825]
Like this:
https://twitter.com/Stewart_Constru/status/865169983411814401
https://medium.com/@dschnr/using-headless-chrome-as-an-automated-screenshot-tool-4b07dffba79a

Possibly using Headless Chrome? 
https://developers.google.com/web/updates/2017/04/headless-chrome

+ Generate Frames
+ Compile Frames to GIF / MP4
+ Save GIF / MP4 to Archives

Assigning to @affan00 as this might be a relatively easy opportunity for him to dip his toe into using this tool or similar.

**Comment by azharmalik3** [comment]
Done.
