### ISSUE TITLE
Reduce # of Models & Vendors

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#832]
- [x] Backup the data - we may want it in the future.
- [x] Where all models for 1 vendor are the same, then remove all models and create just "Default"
- [ ] Where all models are not the same e.g. Axis / Hik ... then plan a strategy to reduce to the minimum.

Do 1 & 2 First , then discuss 3

**Comment by azharmalik3** [comment]
@marcoherbst completed point 1 and 2. Now want to discuss point-3.

**Comment by marcoherbst** [comment]
@azharmalik3 ok, great. Could the start of this conversation be a proposal / suggestion from you? and then we'll work from there.....

Probably in Google Sheets showing current + proposed

**Comment by marcoherbst** [comment]
Closing - going into 811
