### ISSUE TITLE
Compare Tool - Export Function

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#839]
As a user, I want to share / export an example of a compare.

I click on "Share this Compare" which will ask me to give the compare a name "e.g. October Progress" and will copy the 2 chosen images to a public folder. It will create a few options for me:

- [x] Embed Code (with or without animation).
- [x] Animated File (GIF or MP4) (Maybe send to Youtube...)

This is related to issue:
https://github.com/evercam/evercam-server/issues/825

Azhar suggests (I agree) that these compares images are stored in S3.

There may be another button "Compare Archives" which would show us a list of previously created compares. (chosen from a 3 vertical dot menu / hamburger)

**Comment by azharmalik3** [comment]
Done.
