### ISSUE TITLE
Make GIF / MP4 generation faster.

### ISSUE THREAD

**Issue by azharmalik3** [evercam/evercam-server#847]

**Comment by marcoherbst** [comment]
@azharmalik3 one method:

I still think there are FAR too many frames in our GIF / MP4 .... My guess is that it is about 100 ... and I think it could be 5 or 6.

**Comment by azharmalik3** [comment]
@marcoherbst I just go through all steps of GIF/MP4 generation. ImageMagick command (GIF create command) takes maximum 35 sec approx and I tried to reduce generation time using speed params and different FPS settings but it lost the quality of GIF and slow down animate speed but takes the same time to create GIF.

**Comment by marcoherbst** [comment]
I think this is a dead issue. No need to go too deep on this. Closing.
