### ISSUE TITLE
Swagger UI

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#862]
Recreate this for all endpoints. Beautifully done with models and complete documentation.

Target: A really good version 1.

`/cameras/:id/nvr/stream` not be added because this endpoint is used to start the local-recording stream.

We will add timelapse-recording endpoints when this feature available for all users (Now it's only available for construction users).

`/timelapses`
`/cameras/:id/timelapses/:timelapse_id`
`/cameras/:id/timelapses`
`/cameras/:id/timelapses/:timelapse_id` 
`/cameras/:id/timelapses/:timelapse_id`
`/cameras/:id/apps/timelapse-recording` 
`/cameras/:id/apps/timelapse-recording`
`/cameras/:id/timelapse/recordings/snapshots/:year/:month/days`
`/cameras/:id/timelapse/recordings/snapshots/:year/:month/:day`
`/cameras/:id/timelapse/recordings/snapshots/:timestamp`

`/cameras/:id/nvr/snapshots/extract` This endpoint used to send snapshot extraction request from NVR and it is only available for construction use. So, we can't add into swagger doc.

**Comment by marcoherbst** [comment]
@Ali7862 please note in comments whatever is not complete (And why) and then you can close this issue. Well done.

**Comment by marcoherbst** [comment]
@Ali7862 if this is done, close it.

**Comment by Ali7862** [comment]
It's done.
