### ISSUE TITLE
Local extraction should restart from where it stopped.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#870]
When
  - The system gets a restart.
  - When the camera went offline.

Extraction will end.

It should 
   - Get paused in case of Camera offline.
   - Resume from where it stopped.

**Comment by marcoherbst** [comment]
@ijunaid8989 this is an admin task or a server task?

**Comment by ijunaid8989** [comment]
@marcoherbst its a server task.

**Comment by ijunaid8989** [comment]
Its done.
