### ISSUE TITLE
User Type: Read Only + Share

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#874]
Ref: This doc:
https://docs.google.com/spreadsheets/d/1SxhKjGvgaFgFZSmPLSpkggHtUEyQccYN9JnhIhF1aNo/edit#gid=0

**Comment by azharmalik3** [comment]
@marcoherbst Completed Read-Only + Share rights for sharing tab according to `Roles & Capabilities Sheet`.

According to column [E14](https://docs.google.com/spreadsheets/d/1SxhKjGvgaFgFZSmPLSpkggHtUEyQccYN9JnhIhF1aNo/edit#gid=0&range=E14) read-only+share right user can view recordings settings. Is this correct?
