### ISSUE TITLE
Local Extraction upload to DropBox issue.

### ISSUE THREAD

**Issue by ijunaid8989** [evercam/evercam-server#900]
Local extraction is working fine but e.g

Extraction for 1177: 
![image](https://user-images.githubusercontent.com/13561999/38011570-5b2b8dc6-3277-11e8-984f-43641e7be40d.png)
Images came in were 4131, but uploaded to DropBox are 2659,

1472 Images are missing to upload.

Expected Issue:

![image](https://user-images.githubusercontent.com/13561999/38011924-cf3a9d6e-3278-11e8-8509-16b5772820d0.png)

Dropbox uploads timeout, but timeouts are only 21 for past 3 days, and Images missing are greater than 21.

**Comment by marcoherbst** [comment]
I'm putting this into this Milestone. 

In your shoes, I would first tackle the timeout and then look into any remaining issues.

Also, keep in mind we can use alternatives to Dropbox, but only once you understand where the issue lies.

**Comment by marcoherbst** [comment]
@ijunaid8989 is this still an issue?

**Comment by marcoherbst** [comment]
@ijunaid8989 I'm moving this into a current milestone for you to look at, please.

**Comment by ijunaid8989** [comment]
@marcoherbst Okay.

**Comment by marcoherbst** [comment]
@ijunaid8989 
reminder

**Comment by ijunaid8989** [comment]
Right now we are using a single request method to upload a file on Dropbox, which means one request is one session and dropbox giving an error as **too many write operations**.

We decided to change it to upload session, in which the First request will create a session and return a session ID. which will go as parameters in all next requests.

1. Start session
2. append data to the session
3. Complete the batch.

In this way, all files will be moving in one session not one session per each request.

**Things to handle**:

Sessions ID can be used for 48 hours, that is the expiry.

Now as we are resuming the local extraction on application restart.
1. Session Id will be lost, so we need to create a new session from the resuming  image upload
2. In case extraction may take more than 48 hours, so renew the session again. (I have done some local extraction which took more than 2 days even.)

**Comment by ijunaid8989** [comment]
I tried to give time delay between requests but it didn't work, and I studied the documentation of Dropxbox api to send multiple files in a session, I have tested it but I am kind of confused with this because its not working for me the same way it should work, due to some offset values. the option where we end the session it says you can commit many files at once in users account but then it also says you can send one max size file in session with chunks so I am not sure either it's for our use or not.

**Comment by ijunaid8989** [comment]
https://www.dropboxforum.com/t5/API-Support-Feedback/too-many-write-operations-when-uploading-files/m-p/353101#M20194

**Comment by ijunaid8989** [comment]
This is working fine now, there are no `too many write operations` errors.

We are uploading each file on upload session start. and then closing chunks of 1000 files at once to Dropbox account. This has resolved the problem.

**Comment by ijunaid8989** [comment]
its done.
