### ISSUE TITLE
On deleting camera from user account it should also delete its related snapmails.

### ISSUE THREAD

**Issue by affan00** [evercam/evercam-server#937]
These are the scenarios here:
1) When a camera has been deleted from user account than the snapmails of that camera should also be removed from users account. (When a camera is shared with User.)
2) when a camera has been deleted from evercam than all the snapmails of that camera should also be removed from evercam. (When a user is an owner of the camera)
3) If all cameras are removed from a snapmail then the snapmail should be deleted.

**Comment by azharmalik3** [comment]
Fixed.
