### ISSUE TITLE
Review Seaweed Security

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#947]
I need your ideas on this. We will copy S3 best practice, I imagine.

This is next task after EoT.

**Comment by ijunaid8989** [comment]
As far as POST request concerns, we can manage that through seaweedfs itself.

there is an option in seaweedfs master and volume as
```
  -whiteList string
    	comma separated Ip addresses having to write permission. No limit if empty.
```

We can give some IPs which will have write requests.

**Comment by marcoherbst** [comment]
https://github.com/chrislusf/seaweedfs/wiki/Use-Cases#securing-seaweedfs

**Comment by ijunaid8989** [comment]
https://github.com/chrislusf/seaweedfs/issues/672

**Comment by ijunaid8989** [comment]
Summary of events related to this issue.

https://github.com/chrislusf/seaweedfs/issues/672#issuecomment-404407165
https://github.com/chrislusf/seaweedfs/issues/672#issuecomment-404408228
https://github.com/chrislusf/seaweedfs/issues/672#issuecomment-404495402

I think -whiteList parameter wasn't tested enough so there are many issues in here.

If you place the master filer's own IP, it will accept requests from `localhost` as well. And If you remove the filer's ip. It will not let you make any request.

**Comment by marcoherbst** [comment]
Closing this. We can do more work on it another time, esp after moving to Seaweed v3 API

**Comment by chrislusf** [comment]
FYI: https://github.com/chrislusf/seaweedfs/wiki/Security-Overview
