### ISSUE TITLE
Transcode a lower res(VGA) HLS live stream.

### ISSUE THREAD

**Issue by marcoherbst** [evercam/evercam-server#99]
- [ ] Creating a lowres stream for mobile

This ticket had a heap of items in it. Reducing to just creating a VGA stream for mobile.

**Comment by mosic** [comment]
Relevant link: http://www.helping-squad.com/transcoding-your-video-with-nginx/

**Comment by marcoherbst** [comment]
GStreamer chat with Dmitry:
https://docs.google.com/document/d/1tlmpRywKXIbgBli9TFELLq_zBsdBbw8y0zTqEBamVk8/edit

GStreamer general list of problems, with some comments from Philipe:
https://docs.google.com/document/d/1tlmpRywKXIbgBli9TFELLq_zBsdBbw8y0zTqEBamVk8/edit

M

**Comment by marcoherbst** [comment]
@mosic  ....  This is a duplicate of : 
https://github.com/evercam/evercam-devops/issues/12

Or, it needs to be here too?

**Comment by mosic** [comment]
@marcoherbst Good point, closed the other one.

**Comment by marcoherbst** [comment]
Not needed
